//! Shared types for `core::trees`. Pure data — no rusqlite, no SQL.
//!
//! Every public type the rest of the crate consumes lives here. The
//! `Db` struct's internals (the `rusqlite::Connection` mutex) are
//! kept private to the `trees` module; see `super::storage` for the
//! constructor.

use std::path::PathBuf;
use std::sync::Mutex;

use serde::{Deserialize, Serialize};

use crate::cluster::{Algorithm, LeidenParams, SummarizeMode};

/// Bumped only when on-disk schema changes. Pre-1.0 policy: a mismatch
/// is an error; delete `.hiker/trees.db` and rebuild.
pub const SCHEMA_VERSION: i32 = 1;

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("sqlite: {0}")]
    Sqlite(#[from] rusqlite::Error),
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("json: {0}")]
    Json(#[from] serde_json::Error),
    #[error("schema version mismatch: db is v{found}, binary expects v{expected}")]
    VersionMismatch { found: i32, expected: i32 },
    #[error("tree not found: {0}")]
    TreeNotFound(String),
    #[error("node not found: tree={tree_id} node={node_id}")]
    NodeNotFound { tree_id: String, node_id: String },
    #[error("connection mutex poisoned")]
    Poisoned,
}

impl From<Error> for crate::errors::HikerError {
    fn from(e: Error) -> Self {
        crate::errors::HikerError::Io(e.to_string())
    }
}

pub type TreeId = String;
pub type NodeId = String;
pub type NoteId = String;

/// Per `cluster-editor-tree-shape`. Three kinds, all flat — children are
/// implied by `parent_id` in `cluster_nodes`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum NodeKind {
    Cluster,
    Leaf,
    OutlierBucket,
}

impl NodeKind {
    pub(super) const fn as_str(self) -> &'static str {
        match self {
            NodeKind::Cluster => "cluster",
            NodeKind::Leaf => "leaf",
            NodeKind::OutlierBucket => "outlier-bucket",
        }
    }
}

/// Per `cluster-editor-policy-types`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum NodePolicy {
    Tag {
        slug: String,
        #[serde(default)]
        require_review: bool,
    },
    Move {
        folder: String,
        #[serde(default)]
        require_review: bool,
    },
    Freeze,
}

/// In-memory editable shape per `cluster-editor-tree-shape`. Hydrated
/// from a single row in `cluster_nodes`; children are looked up via the
/// `(tree_id, parent_id)` index when the consumer needs them.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EditableNode {
    pub id: NodeId,
    pub parent: Option<NodeId>,
    pub kind: NodeKind,
    /// Present only on leaves.
    pub note_ref: Option<NoteId>,
    /// User-editable label. Cluster basename for leaves; LLM-proposed for
    /// clusters until the user edits it.
    pub name: String,
    /// User-editable. Empty on leaves.
    pub summary: String,
    pub user_edited_name: bool,
    pub user_edited_summary: bool,
    pub policy: Option<NodePolicy>,
    /// Present on clusters; L2-normalized.
    pub centroid: Option<Vec<f32>>,
    /// 0.0-1.0 from build pass; preserved through edits.
    pub confidence: f32,
    /// Per `cluster-summary-staleness-counter`.
    pub summary_membership_churn: u32,
}

/// Row-shaped DTO for `cluster_trees`. Per `cluster-build-scope` /
/// `cluster-build-method`, scope + method + params are persisted on the
/// tree row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TreeRow {
    pub id: TreeId,
    pub name: String,
    /// `one-shot` | `saved-triage` per the spec.
    pub source: String,
    /// `draft` | `applied` | `saved-as-triage` per the spec.
    pub state: String,
    /// JSON of `BuildScope` (per `clustering.md`); free-form here since
    /// the cluster module owns the shape.
    pub scope_json: String,
    /// JSON of `BuildMethod`; carries params inside.
    pub method_json: String,
    pub created_at_ms: i64,
    /// Vault rev at build time; advisory.
    pub vault_snapshot: Option<String>,
}

/// Insert payload for a new tree row. `id` is generated by the caller if
/// they want to address the tree before insert; pass `None` and we pick
/// a ULID.
#[derive(Debug, Clone)]
pub struct TreeInsert {
    pub id: Option<TreeId>,
    pub name: String,
    pub source: String,
    pub state: String,
    pub scope_json: String,
    pub method_json: String,
    pub vault_snapshot: Option<String>,
}

/// Insert payload for a single node. Centroid is packed as little-endian
/// f32 bytes.
#[derive(Debug, Clone)]
pub struct NodeInsert {
    pub node_id: NodeId,
    pub parent_id: Option<NodeId>,
    pub kind: NodeKind,
    pub note_id: Option<NoteId>,
    pub name: String,
    pub summary: String,
    pub user_edited_name: bool,
    pub user_edited_summary: bool,
    pub policy: Option<NodePolicy>,
    pub centroid: Option<Vec<f32>>,
    pub confidence: f32,
    pub summary_membership_churn: u32,
}

/// Append-only history row. Per `cluster-editor-edit-history`. `args`
/// and `undo_args` are caller-shaped JSON so this module stays neutral
/// about the operation vocabulary.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HistoryEntry {
    pub seq: i64,
    pub ts_ms: i64,
    pub op: String,
    pub args_json: String,
    pub undo_args_json: String,
}

// ── Ops-framework types ───────────────────────────────────────────────
//
// `Db::split_cluster` / `Db::plan_summarize_sweep` /
// `Db::apply_rollup` form the three "Operations framework" ops per
// `clustering.md`'s ops-framework section. Each carries its own
// param / outcome struct.

/// Output of `Db::split_cluster`. Per `cluster-op-split`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SplitOutcome {
    pub new_clusters: Vec<NodeId>,
    pub total_levels: u8,
    /// Note ids that landed in the OUTLIER bucket at any branch of the
    /// recursive split. The caller decides whether to
    /// route these into the tree's outlier bucket or surface them to
    /// the user — `split_cluster` itself doesn't touch outlier nodes.
    pub outliers: Vec<NoteId>,
}

/// Scope discriminator for `Db::plan_summarize_sweep`. Per
/// `cluster-op-summarize-sweep`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum SummarizeScope {
    /// Every cluster row in the (sub)tree.
    All,
    /// `WHERE summary_membership_churn > 0 OR summary IS NULL OR summary
    /// = '' OR name IS NULL OR name = ''`.
    StaleOrUnfilled,
    /// The listed ids only; missing ids are dropped.
    Subset { ids: Vec<NodeId> },
}

/// Params for `Db::plan_summarize_sweep`. Per `cluster-op-summarize-sweep`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SummarizeParams {
    pub scope: SummarizeScope,
    /// Optional subtree filter — when set, only nodes under (or equal
    /// to) `subtree_root` are considered.
    #[serde(default)]
    pub subtree_root: Option<NodeId>,
    /// Honored only when `subtree_root` is set. Default `true`.
    #[serde(default = "default_summarize_recursive")]
    pub recursive: bool,
    /// Carried through to the per-cluster `RaptorSummarize` task. The
    /// queue's existing summarize worker reads it from the task payload;
    /// kept on the params struct so callers can pass it through `Db`.
    #[serde(default)]
    pub summarize_mode: SummarizeMode,
    /// Default `false` — user-edited rows are preserved unless this
    /// flag is explicitly opted-into.
    #[serde(default)]
    pub overwrite_user_edited: bool,
}

const fn default_summarize_recursive() -> bool {
    true
}

/// Submission plan returned by `Db::plan_summarize_sweep`. The
/// caller consumes this and performs the actual queue submission (the
/// queue API is async; `Db` stays sync per module discipline).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SummarizePlan {
    pub tree_id: TreeId,
    /// Stable identifier for the umbrella `ClusterSummarize` task's
    /// metadata — one of `"all"`, `"stale-or-unfilled"`, `"subset"`.
    pub scope_kind: String,
    /// Cluster node ids in submission order (deepest-first). The caller
    /// submits one `RaptorSummarize` task per id.
    pub enqueued: Vec<NodeId>,
    pub skipped_user_edited: Vec<NodeId>,
    pub skipped_fresh: Vec<NodeId>,
}

/// Params for `Db::apply_rollup`. Per `cluster-op-rollup`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RollupParams {
    pub input_node_ids: Vec<NodeId>,
    #[serde(default)]
    pub algorithm: Algorithm,
    #[serde(default)]
    pub leiden: LeidenParams,
    #[serde(default = "default_rollup_min_cluster_size")]
    pub min_cluster_size: u32,
    #[serde(default)]
    pub new_layer_name_pattern: Option<String>,
}

const fn default_rollup_min_cluster_size() -> u32 {
    2
}

/// Per-input shape produced by `Db::validate_rollup_inputs` and
/// consumed by `Db::apply_rollup`. Carries the summary text the
/// caller embeds + the prior parent so the history snapshot can undo.
#[derive(Debug, Clone)]
pub struct RollupInput {
    pub node_id: NodeId,
    pub summary: String,
    pub prior_parent: Option<NodeId>,
}

/// Output of `Db::apply_rollup`. Per `cluster-op-rollup`. The
/// `Refused` variant carries the reason as a static string so the UI
/// can surface it verbatim without consulting a translation table.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum RollupOutcome {
    Inserted { new_parent_ids: Vec<NodeId> },
    Refused { reason: &'static str },
}

/// Owner of `vault/.hiker/trees.db`. Single-writer; reads share the same
/// connection under a mutex (mirrors `core::staging`'s shape — the
/// concurrency profile is "infrequent user edits," not the high-throughput
/// indexer drain `core::store` is tuned for).
pub struct Db {
    pub(super) conn: Mutex<rusqlite::Connection>,
    pub(super) db_path: PathBuf,
}
