[package]
name = "hiker-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "hiker_ui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde.workspace = true
serde_json.workspace = true
hiker-core.workspace = true
hiker-mcp-server = { path = "../../mcp-server" }
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
