// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[acp]` section. Configures the optional Agent Client Protocol backend
 * for the chat panel. When `command` is non-empty, the chat panel routes
 * through an external ACP agent instead of the built-in basic agent loop.
 * The `command` value is the full command line to launch the agent (e.g.
 * `"auggie --acp"`, `"gemini --acp"`, `"cursor --acp"`). The first
 * whitespace-delimited word is the binary; the rest are arguments.
 * The agent binary must be installed and on PATH independently.
 * See `docs/acp.md`.
 *
 * status: llm-acp-client-optional
 */
export type AcpConfig = { 
/**
 * Full command line to launch the ACP agent. Empty string means
 * ACP is disabled. Split on whitespace; first token = binary,
 * remainder = args.
 */
command: string, };
