// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcpConfig } from "./AcpConfig";
import type { EditorConfig } from "./EditorConfig";
import type { IndexingConfig } from "./IndexingConfig";
import type { LlmConfig } from "./LlmConfig";
import type { McpConfig } from "./McpConfig";
import type { SearchConfig } from "./SearchConfig";
import type { StagingConfig } from "./StagingConfig";
import type { SuggestionsConfig } from "./SuggestionsConfig";
import type { TasksConfig } from "./TasksConfig";
import type { TrailsConfig } from "./TrailsConfig";
import type { VaultConfig } from "./VaultConfig";

/**
 * Top-level config struct loaded from the merged user+vault TOML.
 */
export type Config = { schema_version: number, editor: EditorConfig, indexing: IndexingConfig, vault: VaultConfig, search: SearchConfig, mcp: McpConfig, llm: LlmConfig, tasks: TasksConfig, trails: TrailsConfig, acp: AcpConfig, staging: StagingConfig, suggestions: SuggestionsConfig, };
