// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditorConfig = { render_txt_as_markdown: boolean, live_preview: boolean, word_wrap: boolean, show_line_numbers: boolean, show_whitespace: boolean, show_chunk_boundaries: boolean, hide_frontmatter: boolean, intraline_diff: boolean, tab_size: number, };
