// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Note-id stamping policy. See `docs/trails.md` §"Note ID stamping policy".
 *
 * status: note-id-stamping
 */
export type IdStampingMode = "all" | "lazy";
