// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdStampingMode } from "./IdStampingMode";

export type IndexingConfig = { model: string, batch_size: number, ignored_paths: Array<string>, 
/**
 * Controls when notes get their `hiker.id` stamped into frontmatter.
 * `lazy` (default) stamps only when a note becomes a reference target
 * (e.g. trail waypoint, future wikilink). `all` stamps every note on
 * first ingest. Both modes share the invariant that any *referenced*
 * note is stamped.
 *
 * status: note-id-stamping
 */
id_stamping: IdStampingMode, };
