// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[llm.agent]` — basic agent loop tunables. Defaults match the
 * circuit-breaker numbers pinned in `llm.md`.
 *
 * status: agent-iteration-cap-prompt
 * status: agent-tool-call-timeout
 */
export type LlmAgentConfig = { iteration_cap: number, tool_timeout_secs: number, };
