// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LlmAuditConfig = { 
/**
 * Mirror of `[mcp.audit] log_full_input`. When false (default), the
 * JSONL audit log records call metadata but redacts large prompt
 * bodies.
 */
log_full_prompt: boolean, };
