// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[llm.background]` — config for debounced background LLM features
 * (auto-tagging, summarization, etc.). Stub in v3 — `review_required`
 * is the only field that ships now; the rest land when their backing
 * features do.
 *
 * status: agent-write-review-mode
 */
export type LlmBackgroundConfig = { 
/**
 * When true, debounced background LLM features write to staging
 * instead of mutating frontmatter directly. Default false (off).
 */
review_required: boolean, };
