// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LlmAgentConfig } from "./LlmAgentConfig";
import type { LlmAuditConfig } from "./LlmAuditConfig";
import type { LlmBackgroundConfig } from "./LlmBackgroundConfig";
import type { LlmLimitsConfig } from "./LlmLimitsConfig";
import type { LlmProviderConfig } from "./LlmProviderConfig";

/**
 * `[llm]` section. Configures generative LLM access for `core::llm` and
 * the basic agent loop (`core::agent`). Mirrors the shape pinned in
 * `docs/llm.md` §`core::llm` and the v3.5 stub in `docs/settings.md`.
 *
 * status: llm-providers-config
 */
export type LlmConfig = { 
/**
 * Master switch. When false, `core::llm` is treated as unavailable
 * (background / fan-out / chat panel all no-op). Reserved for
 * `llm-disable-mode`; left here so the loader doesn't reject the key
 * once that slug lands.
 */
enabled: boolean, provider: LlmProviderConfig, limits: LlmLimitsConfig, agent: LlmAgentConfig, audit: LlmAuditConfig, background: LlmBackgroundConfig, };
