// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[llm.provider]` — backend selection and connection-shaped knobs. API
 * keys are *never* stored in TOML; `api_key_env` names an environment
 * variable that the runtime reads at provider construction time. Empty
 * strings on `api_key_env` / `base_url` are treated as unset (the TOML
 * auto-create writes the field even when blank, so the loader has to
 * tolerate that case rather than aborting).
 */
export type LlmProviderConfig = { 
/**
 * Backend id (`anthropic` / `openai` / `ollama` / `google` / ...). The
 * canonical list lives in graniet/`llm`'s `LLMBackend::FromStr`; the
 * runtime validates this when the client is built.
 */
backend: string, 
/**
 * Model id within the chosen backend.
 */
model: string, 
/**
 * Name of the env var holding the API key. Empty = no key (e.g. local
 * Ollama). Used as the fallback when `api_key` (user-scope literal)
 * is empty.
 */
api_key_env: string, 
/**
 * User-scope literal API key. Plain text on disk in the platform
 * config dir; takes precedence over `api_key_env` when set. The
 * eligibility list refuses writes to this field from the vault
 * TOML so a synced vault can't carry the secret. Empty by default;
 * users who want shell-managed keys should leave this empty and
 * set `api_key_env`. See `llm.md` §`[llm-providers-config]`.
 */
api_key: string, 
/**
 * Optional override (Ollama URL, OpenAI-compatible proxy, etc.).
 */
base_url: string, };
