// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpAuditConfig = { 
/**
 * Mirror of `[llm.audit] log_full_prompt`. When false (default), the
 * JSONL audit log records call metadata but redacts large input bodies.
 */
log_full_input: boolean, };
