// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpAuditConfig } from "./McpAuditConfig";
import type { McpToolsConfig } from "./McpToolsConfig";

/**
 * `[mcp]` section. Configures the in-process MCP server (see `docs/mcp.md`).
 * Loader lands alongside the v3 milestone — until then the section is
 * recognized so users can enable/disable the server and tune top_k caps.
 *
 * status: mcp-config-section
 */
export type McpConfig = { enabled: boolean, 
/**
 * Bind host. Defaults to `127.0.0.1` (loopback-only, matching the
 * localhost-trust auth model). Anything else exposes vault contents
 * to whoever can reach the listening port — the settings UI shows
 * a warning. See `mcp-bind-host-configurable`.
 */
host: string, 
/**
 * `0` = ephemeral OS-assigned port; otherwise bind that fixed port.
 */
port: number, 
/**
 * Vault-relative path to the JSON discovery file written on bind and
 * removed on shutdown.
 */
discovery_file: string, 
/**
 * Cap on agent-requested `top_k` for `search_notes` / `related_notes`.
 */
max_top_k: number, tools: McpToolsConfig, audit: McpAuditConfig, };
