// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpToolsConfig = { 
/**
 * Master gate for the write tools (`write_note`, `set_frontmatter`,
 * `apply_tag`, `remove_tag`). Kept for backwards compatibility with
 * existing TOMLs — when false, every write tool refuses with `1004
 * disabled` regardless of the per-tool flags below.
 */
writes_enabled: boolean, 
/**
 * If true, agents passing `scope` can fetch redacted bodies.
 * Conservative default (false) per spec.
 */
allow_redacted_lookup: boolean, 
/**
 * When true, MCP write tools (`write_note`, `set_frontmatter`,
 * `apply_tag`, `remove_tag`) route through `core::staging::propose()`
 * instead of applying directly. Default false — agents write directly
 * + append a changelog row (existing behavior).
 */
review_required: boolean, search_notes_enabled: boolean, get_note_enabled: boolean, related_notes_enabled: boolean, write_note_enabled: boolean, edit_note_enabled: boolean, set_frontmatter_enabled: boolean, apply_tag_enabled: boolean, remove_tag_enabled: boolean, task_checkout_enabled: boolean, task_submit_enabled: boolean, task_fail_enabled: boolean, task_heartbeat_enabled: boolean, task_list_enabled: boolean, };
