// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recency-bias weighting for the semantic engine. `Off` = no recency
 * blend (default); `Mild` / `Strong` mix mtime rank into the score via
 * the same RRF k=60 shape as cross-mode fusion (weights 0.5 / 1.0).
 */
export type RecencyBias = "off" | "mild" | "strong";
