// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchSectionsConfig = { results_expanded: boolean, related_expanded: boolean, };
