// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[search.lexical]` — per-mode option flags surfaced via the right-click
 * options menu on the Lexical (`Aa`) toggle. Defaults preserve current
 * behavior (everything off) so existing users see no change until they
 * reach into the menu.
 *
 * status: search-lexical-options
 */
export type SearchLexicalConfig = { case_sensitive: boolean, diacritic_sensitive: boolean, prefix_match: boolean, phrase_mode: boolean, };
