// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecencyBias } from "./RecencyBias";

/**
 * `[search.semantic]` — per-mode option flags surfaced via the right-click
 * options menu on the Semantic (brain) toggle.
 *
 * status: search-semantic-options
 */
export type SearchSemanticConfig = { 
/**
 * Cosine-similarity floor; hits below this are dropped before fusion.
 * Range 0.00–0.95 in 0.05 steps; default 0.00 (no filter).
 * status: search-semantic-min-similarity
 */
min_similarity: number, 
/**
 * Override of `PER_BACKEND_TOP_K` for the semantic side only. Range
 * 5–100; default 25 (matches the lexical side).
 * status: search-semantic-top-k-override
 */
top_k: number, 
/**
 * RRF blend of `notes.mtime` rank into the semantic score; off/mild/strong.
 * status: search-semantic-recency-bias
 */
recency_bias: RecencyBias, };
