// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchLexicalConfig } from "./SearchLexicalConfig";
import type { SearchModesConfig } from "./SearchModesConfig";
import type { SearchSectionsConfig } from "./SearchSectionsConfig";
import type { SearchSemanticConfig } from "./SearchSemanticConfig";

/**
 * `[search]` section. Holds discovery-panel state: which backends run by
 * default (mode toggles), and the per-section collapsed/expanded state
 * inside the panel. Vault-scoped via `settings-write-back`.
 */
export type SearchConfig = { modes: SearchModesConfig, sections: SearchSectionsConfig, lexical: SearchLexicalConfig, semantic: SearchSemanticConfig, };
