// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a write-back targets the per-user TOML or the per-vault TOML.
 */
export type SettingsScope = "user" | "vault";
