// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Active sidebar mode. Persisted per-vault under `vault.sidebar_mode`.
 * status: sidebar-mode-switcher
 */
export type SidebarMode = "files" | "clusters" | "trails";
