// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[staging]` section. Behavior that applies regardless of which producer
 * staged a proposal. See `docs/settings.md` §`[staging]` config section.
 *
 * status: staging-config-section
 */
export type StagingConfig = { 
/**
 * When `true`, the `applyable → conflicted` state transition
 * immediately invokes `reject(id)`. Live-applied. Default false.
 *
 * status: staging-auto-reject-on-conflict
 */
auto_reject_on_conflict: boolean, 
/**
 * GC age threshold consumed by `Staging::gc` on vault open. Lifts the
 * previously-hardcoded 14-day value.
 */
retention_days: number, };
