// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TriageConfig } from "./TriageConfig";

/**
 * `[suggestions]` + `[suggestions.triage]` config. See
 * `docs/suggestions.md` §"`[suggestions.triage]` config section". The
 * outer table currently only carries the triage subsection; the
 * `tag_field` and other knobs land alongside their feature wiring.
 *
 * status: triage-review-required
 * status: triage-staging-proposals
 */
export type SuggestionsConfig = { triage: TriageConfig, };
