// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirectWorkerConfig } from "./DirectWorkerConfig";
import type { LeaseConfig } from "./LeaseConfig";
import type { WorkerPreferenceCfg } from "./WorkerPreferenceCfg";

/**
 * `[tasks]` section. Configures the unified work queue (`core::tasks`).
 * See `docs/task-queue.md`.
 *
 * status: task-queue-settings-section
 */
export type TasksConfig = { worker_preference: WorkerPreferenceCfg, terminal_retention_secs: number, direct_worker: DirectWorkerConfig, 
/**
 * Whether the in-process basic chat agent gets the `task_*` MCP
 * tools advertised in its tool set. External rmcp clients are
 * unaffected — they always see `task_*` when `[mcp] enabled = true`.
 */
expose_to_chat_agent: boolean, lease: LeaseConfig, };
