// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[trails]` section. Configures trail-doc placement and other vault-wide
 * trail policy. See `docs/trails.md`.
 *
 * status: trails-default-location
 */
export type TrailsConfig = { 
/**
 * Default directory for newly-created trail-docs. Vault-relative.
 * Empty string places trails at vault root. Auto-created on first
 * trail. Vault-scope eligible per `settings-write-back`.
 */
new_trail_dir: string, };
