// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TreeSortBy } from "./TreeSortBy";

export type TreeConfig = { sort_by: TreeSortBy, };
