// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `[suggestions.triage]` subsection. Triage-level behavior — auto-accept
 * gating, source-folder safety boundary, optional scheduled re-run.
 *
 * status: triage-review-required
 */
export type TriageConfig = { 
/**
 * When `true`, every triage match stays pending in `staging.db`
 * until the user accepts. When `false`, `auto-*` matches auto-accept
 * at insert time. Live-applied.
 */
review_required: boolean, 
/**
 * Source-folder boundary for triage moves. Triage never produces a
 * `move_note` row whose `source_path` is outside this folder. Also
 * drives the on-save trigger's default folder.
 */
scope: string, 
/**
 * Duration-string grammar (`30m` / `1h` / `6h` / `24h` / `7d`); empty
 * disables. Per `cluster-editor-triage-scheduled-rerun`. NOTE: the spec
 * calls for cron-shape values (e.g. `"0 3 * * *"`); the runtime currently
 * accepts only the duration grammar above and silently logs + disables
 * anything else. Cron-shape support is tracked as
 * `cluster-editor-triage-scheduled-rerun-cron-syntax`.
 */
scheduled_rerun: string, 
/**
 * Opt-in: re-run triage when a note's embedding shifts beyond
 * `modified_rerun_cosine_guard` distance from its last triaged
 * state. Per `cluster-editor-triage-modified-rerun`. Default off.
 */
modified_rerun: boolean, 
/**
 * Cosine-distance threshold gating the modified-note rerun
 * (0.0 = always re-run; 1.0 = never). Default 0.15 — typical save
 * noise sits below this; meaningful edits clear it.
 */
modified_rerun_cosine_guard: number, };
