// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SidebarMode } from "./SidebarMode";
import type { TreeConfig } from "./TreeConfig";

export type VaultConfig = { recent: Array<string>, default: string | null, sidebar_open: boolean, related_open: boolean, trash_expanded: boolean, 
/**
 * Chat region height as a fraction of the discovery panel height.
 * status: chat-panel-default-height
 */
chat_height: number, 
/**
 * Sidebar column width in CSS pixels.
 * status: side-panel-resize
 */
sidebar_width: number, 
/**
 * Discovery (right) column width in CSS pixels.
 * status: side-panel-resize
 */
discovery_width: number, 
/**
 * Surface `.hiker/sessions/` as a virtual top-level "Sessions" group
 * in the tree. Default off — sessions stay hidden alongside other
 * `.hiker/` sidecars. Search and related-notes always include
 * sessions regardless of this toggle.
 * status: chat-session-show-in-tree-toggle
 */
show_sessions_in_tree: boolean, 
/**
 * Active sidebar mode (Files / Cluster trees / Trails).
 * status: sidebar-mode-switcher
 */
sidebar_mode: SidebarMode, 
/**
 * Vault-relative path of the currently active trail-doc, or `None`
 * if no trail is active. At most one active trail per vault. Persisted
 * via `set_setting` so it survives restarts.
 *
 * status: active-trail-state
 */
active_trail: string | null, 
/**
 * User-set chat input height in CSS pixels, or 0 for auto-grow mode.
 */
chat_input_height: number, tree: TreeConfig, };
