pub mod agent;
pub mod audit;
pub mod autosave;
pub mod changes;
pub mod chunker;
pub mod config;
pub mod diff;
pub mod embed;
pub mod error;
pub mod frontmatter;
pub mod hash;
pub mod indexer;
pub mod llm;
pub mod observability;
pub mod prompts;
pub mod ops;
pub mod search;
pub mod sessions;
pub mod store;
pub mod tasks;
pub mod trash;
pub mod vault;
pub mod watcher;

pub use error::HikerError;
pub use hash::hash_str;
pub use vault::{DirEntryDto, EntryKind, Vault};
