//! Cluster-tree storage. See `docs/cluster-editor.md` §"Tree storage:
//! `trees.db`" and `docs/clustering.md` for the full spec.
//!
//! `core::trees` owns `vault/.hiker/trees.db` — a SQLite database with
//! three tables (`cluster_trees`, `cluster_nodes`, `cluster_tree_history`).
//! Mirrors the module-discipline pattern used by `core::store`,
//! `core::staging`, and `core::changes`: every rusqlite import lives here,
//! callers consume plain Rust types only. Pre-1.0 schema policy is
//! delete-on-bump (no migration code).
//!
//! status: trees-db
//! status: trees-db-schema
//! status: trees-module-discipline
//! status: cluster-editor-tree-shape
//! status: cluster-editor-edit-history

use std::path::{Path, PathBuf};
use std::sync::Mutex;

use rusqlite::{params, Connection, OptionalExtension};
use serde::{Deserialize, Serialize};

/// Bumped only when on-disk schema changes. Pre-1.0 policy: a mismatch
/// is an error; delete `.hiker/trees.db` and rebuild.
pub const SCHEMA_VERSION: i32 = 1;

#[derive(Debug, thiserror::Error)]
pub enum TreesError {
    #[error("sqlite: {0}")]
    Sqlite(#[from] rusqlite::Error),
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
    #[error("json: {0}")]
    Json(#[from] serde_json::Error),
    #[error("schema version mismatch: db is v{found}, binary expects v{expected}")]
    VersionMismatch { found: i32, expected: i32 },
    #[error("tree not found: {0}")]
    TreeNotFound(String),
    #[error("node not found: tree={tree_id} node={node_id}")]
    NodeNotFound { tree_id: String, node_id: String },
}

impl From<TreesError> for crate::error::HikerError {
    fn from(e: TreesError) -> Self {
        crate::error::HikerError::Io(e.to_string())
    }
}

pub type TreeId = String;
pub type NodeId = String;
pub type NoteId = String;

/// Per `cluster-editor-tree-shape`. Three kinds, all flat — children are
/// implied by `parent_id` in `cluster_nodes`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum NodeKind {
    Cluster,
    Leaf,
    OutlierBucket,
}

impl NodeKind {
    fn as_str(self) -> &'static str {
        match self {
            NodeKind::Cluster => "cluster",
            NodeKind::Leaf => "leaf",
            NodeKind::OutlierBucket => "outlier-bucket",
        }
    }
    fn parse(s: &str) -> Option<Self> {
        match s {
            "cluster" => Some(NodeKind::Cluster),
            "leaf" => Some(NodeKind::Leaf),
            "outlier-bucket" => Some(NodeKind::OutlierBucket),
            _ => None,
        }
    }
}

/// Per `cluster-editor-policy-types`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum NodePolicy {
    Tag {
        slug: String,
        #[serde(default)]
        require_review: bool,
    },
    Move {
        folder: String,
        #[serde(default)]
        require_review: bool,
    },
    Freeze,
}

/// In-memory editable shape per `cluster-editor-tree-shape`. Hydrated
/// from a single row in `cluster_nodes`; children are looked up via the
/// `(tree_id, parent_id)` index when the consumer needs them.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EditableNode {
    pub id: NodeId,
    pub parent: Option<NodeId>,
    pub kind: NodeKind,
    /// Present only on leaves.
    pub note_ref: Option<NoteId>,
    /// User-editable label. Cluster basename for leaves; LLM-proposed for
    /// clusters until the user edits it.
    pub name: String,
    /// User-editable. Empty on leaves.
    pub summary: String,
    pub user_edited_name: bool,
    pub user_edited_summary: bool,
    pub policy: Option<NodePolicy>,
    /// Present on clusters; L2-normalized.
    pub centroid: Option<Vec<f32>>,
    /// 0.0-1.0 from build pass; preserved through edits.
    pub confidence: f32,
    /// Per `cluster-summary-staleness-counter`.
    pub summary_membership_churn: u32,
}

/// Row-shaped DTO for `cluster_trees`. Per `cluster-build-scope` /
/// `cluster-build-method`, scope + method + params are persisted on the
/// tree row.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TreeRow {
    pub id: TreeId,
    pub name: String,
    /// `one-shot` | `saved-triage` per the spec.
    pub source: String,
    /// `draft` | `applied` | `saved-as-triage` per the spec.
    pub state: String,
    /// JSON of `BuildScope` (per `clustering.md`); free-form here since
    /// the cluster module owns the shape.
    pub scope_json: String,
    /// JSON of `BuildMethod`; carries params inside.
    pub method_json: String,
    pub created_at_ms: i64,
    /// Vault rev at build time; advisory.
    pub vault_snapshot: Option<String>,
}

/// Insert payload for a new tree row. `id` is generated by the caller if
/// they want to address the tree before insert; pass `None` and we pick
/// a ULID.
#[derive(Debug, Clone)]
pub struct TreeInsert {
    pub id: Option<TreeId>,
    pub name: String,
    pub source: String,
    pub state: String,
    pub scope_json: String,
    pub method_json: String,
    pub vault_snapshot: Option<String>,
}

/// Insert payload for a single node. Centroid is packed as little-endian
/// f32 bytes.
#[derive(Debug, Clone)]
pub struct NodeInsert {
    pub node_id: NodeId,
    pub parent_id: Option<NodeId>,
    pub kind: NodeKind,
    pub note_id: Option<NoteId>,
    pub name: String,
    pub summary: String,
    pub user_edited_name: bool,
    pub user_edited_summary: bool,
    pub policy: Option<NodePolicy>,
    pub centroid: Option<Vec<f32>>,
    pub confidence: f32,
    pub summary_membership_churn: u32,
}

/// Append-only history row. Per `cluster-editor-edit-history`. `args`
/// and `undo_args` are caller-shaped JSON so this module stays neutral
/// about the operation vocabulary.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct HistoryEntry {
    pub seq: i64,
    pub ts_ms: i64,
    pub op: String,
    pub args_json: String,
    pub undo_args_json: String,
}

/// Owner of `vault/.hiker/trees.db`. Single-writer; reads share the same
/// connection under a mutex (mirrors `core::staging`'s shape — the
/// concurrency profile is "infrequent user edits," not the high-throughput
/// indexer drain `core::store` is tuned for).
pub struct Trees {
    conn: Mutex<Connection>,
    db_path: PathBuf,
}

impl Trees {
    /// Open or create the trees db at `<vault_root>/.hiker/trees.db`.
    /// Fails loud on schema-version mismatch (pre-1.0 policy: delete the
    /// file and retry).
    pub fn open(vault_root: &Path) -> Result<Self, TreesError> {
        let hiker_dir = vault_root.join(".hiker");
        std::fs::create_dir_all(&hiker_dir)?;
        let db_path = hiker_dir.join("trees.db");
        let mut conn = Connection::open(&db_path)?;
        configure(&conn)?;
        ensure_schema(&mut conn)?;
        Ok(Self {
            conn: Mutex::new(conn),
            db_path,
        })
    }

    pub fn db_path(&self) -> &Path {
        &self.db_path
    }

    // ── Tree-level operations ────────────────────────────────────────

    /// Insert a new tree row. Returns the tree id (generated when the
    /// caller passes `None`).
    pub fn insert_tree(&self, t: TreeInsert) -> Result<TreeId, TreesError> {
        let id = t.id.unwrap_or_else(crate::store::new_id);
        let now = now_ms();
        let conn = self.conn.lock().expect("trees mutex poisoned");
        conn.execute(
            "INSERT INTO cluster_trees
               (id, name, source, state, scope, method, created_at_ms, vault_snapshot)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
            params![
                id,
                t.name,
                t.source,
                t.state,
                t.scope_json,
                t.method_json,
                now,
                t.vault_snapshot,
            ],
        )?;
        Ok(id)
    }

    /// Look up one tree row by id. Returns `None` if it doesn't exist.
    pub fn get_tree(&self, tree_id: &str) -> Result<Option<TreeRow>, TreesError> {
        let conn = self.conn.lock().expect("trees mutex poisoned");
        let row = conn
            .query_row(
                "SELECT id, name, source, state, scope, method, created_at_ms, vault_snapshot
                 FROM cluster_trees WHERE id = ?1",
                params![tree_id],
                map_tree_row,
            )
            .optional()?;
        Ok(row)
    }

    /// List every tree row, newest first.
    pub fn list_trees(&self) -> Result<Vec<TreeRow>, TreesError> {
        let conn = self.conn.lock().expect("trees mutex poisoned");
        let mut stmt = conn.prepare(
            "SELECT id, name, source, state, scope, method, created_at_ms, vault_snapshot
             FROM cluster_trees ORDER BY created_at_ms DESC",
        )?;
        let rows = stmt
            .query_map([], map_tree_row)?
            .collect::<Result<Vec<_>, _>>()?;
        Ok(rows)
    }

    /// Update a tree's state. Returns `TreeNotFound` if no row matched.
    pub fn set_tree_state(&self, tree_id: &str, state: &str) -> Result<(), TreesError> {
        let conn = self.conn.lock().expect("trees mutex poisoned");
        let n = conn.execute(
            "UPDATE cluster_trees SET state = ?1 WHERE id = ?2",
            params![state, tree_id],
        )?;
        if n == 0 {
            return Err(TreesError::TreeNotFound(tree_id.to_string()));
        }
        Ok(())
    }

    /// Delete a tree row. Cascades to `cluster_nodes` and
    /// `cluster_tree_history` via FK ON DELETE CASCADE.
    pub fn delete_tree(&self, tree_id: &str) -> Result<(), TreesError> {
        let conn = self.conn.lock().expect("trees mutex poisoned");
        conn.execute(
            "DELETE FROM cluster_trees WHERE id = ?1",
            params![tree_id],
        )?;
        Ok(())
    }

    // ── Node-level operations ────────────────────────────────────────

    /// Bulk-insert nodes for a tree under one transaction. Used by the
    /// build pipeline when it lands a fresh tree's initial state.
    pub fn insert_nodes(&self, tree_id: &str, nodes: &[NodeInsert]) -> Result<(), TreesError> {
        let mut conn = self.conn.lock().expect("trees mutex poisoned");
        let tx = conn.transaction()?;
        {
            let mut stmt = tx.prepare(
                "INSERT INTO cluster_nodes
                   (tree_id, node_id, parent_id, kind, note_id, name, summary,
                    user_edited_name, user_edited_summary, policy, centroid,
                    confidence, summary_membership_churn)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13)",
            )?;
            for n in nodes {
                let policy_json = match &n.policy {
                    Some(p) => Some(serde_json::to_string(p)?),
                    None => None,
                };
                let centroid_bytes = n.centroid.as_ref().map(pack_centroid);
                stmt.execute(params![
                    tree_id,
                    n.node_id,
                    n.parent_id,
                    n.kind.as_str(),
                    n.note_id,
                    n.name,
                    n.summary,
                    n.user_edited_name as i32,
                    n.user_edited_summary as i32,
                    policy_json,
                    centroid_bytes,
                    n.confidence as f64,
                    n.summary_membership_churn as i64,
                ])?;
            }
        }
        tx.commit()?;
        Ok(())
    }

    /// Fetch one node, hydrated into an `EditableNode`.
    pub fn get_node(
        &self,
        tree_id: &str,
        node_id: &str,
    ) -> Result<Option<EditableNode>, TreesError> {
        let conn = self.conn.lock().expect("trees mutex poisoned");
        let row = conn
            .query_row(
                NODE_SELECT_SQL,
                params![tree_id, node_id],
                map_editable_node,
            )
            .optional()?;
        row.transpose()
    }

    /// Every node in the tree, in arbitrary order. Caller groups by
    /// `parent` to walk the tree.
    pub fn list_nodes(&self, tree_id: &str) -> Result<Vec<EditableNode>, TreesError> {
        let conn = self.conn.lock().expect("trees mutex poisoned");
        let mut stmt = conn.prepare(
            "SELECT node_id, parent_id, kind, note_id, name, summary,
                    user_edited_name, user_edited_summary, policy, centroid,
                    confidence, summary_membership_churn
             FROM cluster_nodes WHERE tree_id = ?1",
        )?;
        let rows: Vec<EditableNode> = stmt
            .query_map(params![tree_id], map_editable_node)?
            .collect::<Result<Vec<Result<EditableNode, TreesError>>, _>>()?
            .into_iter()
            .collect::<Result<Vec<_>, _>>()?;
        Ok(rows)
    }

    /// Children of a given parent (or the root when `parent_id` is
    /// `None`). Cheap thanks to the `(tree_id, parent_id)` index.
    pub fn children_of(
        &self,
        tree_id: &str,
        parent_id: Option<&str>,
    ) -> Result<Vec<EditableNode>, TreesError> {
        let conn = self.conn.lock().expect("trees mutex poisoned");
        let (sql, rows) = match parent_id {
            Some(pid) => (
                "SELECT node_id, parent_id, kind, note_id, name, summary,
                        user_edited_name, user_edited_summary, policy, centroid,
                        confidence, summary_membership_churn
                 FROM cluster_nodes WHERE tree_id = ?1 AND parent_id = ?2",
                {
                    let mut stmt = conn.prepare(
                        "SELECT node_id, parent_id, kind, note_id, name, summary,
                                user_edited_name, user_edited_summary, policy, centroid,
                                confidence, summary_membership_churn
                         FROM cluster_nodes WHERE tree_id = ?1 AND parent_id = ?2",
                    )?;
                    stmt.query_map(params![tree_id, pid], map_editable_node)?
                        .collect::<Result<Vec<_>, _>>()?
                },
            ),
            None => (
                "(root)",
                {
                    let mut stmt = conn.prepare(
                        "SELECT node_id, parent_id, kind, note_id, name, summary,
                                user_edited_name, user_edited_summary, policy, centroid,
                                confidence, summary_membership_churn
                         FROM cluster_nodes WHERE tree_id = ?1 AND parent_id IS NULL",
                    )?;
                    stmt.query_map(params![tree_id], map_editable_node)?
                        .collect::<Result<Vec<_>, _>>()?
                },
            ),
        };
        let _ = sql;
        rows.into_iter().collect::<Result<Vec<_>, _>>()
    }

    /// Set the policy on a node (or clear it with `None`). Appends a
    /// `set-policy` history entry with both prior and new policy in the
    /// undo payload.
    pub fn set_policy(
        &self,
        tree_id: &str,
        node_id: &str,
        policy: Option<NodePolicy>,
    ) -> Result<(), TreesError> {
        let prior = self.get_node(tree_id, node_id)?.ok_or_else(|| {
            TreesError::NodeNotFound {
                tree_id: tree_id.to_string(),
                node_id: node_id.to_string(),
            }
        })?;
        let policy_json = match &policy {
            Some(p) => Some(serde_json::to_string(p)?),
            None => None,
        };
        {
            let conn = self.conn.lock().expect("trees mutex poisoned");
            conn.execute(
                "UPDATE cluster_nodes SET policy = ?1 WHERE tree_id = ?2 AND node_id = ?3",
                params![policy_json, tree_id, node_id],
            )?;
        }
        let args = serde_json::json!({ "node_id": node_id, "policy": policy });
        let undo = serde_json::json!({ "node_id": node_id, "policy": prior.policy });
        self.append_history(tree_id, "set-policy", &args, &undo)?;
        Ok(())
    }

    /// Rename a node. Stamps `user_edited_name = true`. Appends a
    /// `rename` history entry.
    pub fn rename(&self, tree_id: &str, node_id: &str, new_name: &str) -> Result<(), TreesError> {
        let prior = self.get_node(tree_id, node_id)?.ok_or_else(|| {
            TreesError::NodeNotFound {
                tree_id: tree_id.to_string(),
                node_id: node_id.to_string(),
            }
        })?;
        {
            let conn = self.conn.lock().expect("trees mutex poisoned");
            conn.execute(
                "UPDATE cluster_nodes
                 SET name = ?1, user_edited_name = 1
                 WHERE tree_id = ?2 AND node_id = ?3",
                params![new_name, tree_id, node_id],
            )?;
        }
        let args = serde_json::json!({ "node_id": node_id, "name": new_name });
        let undo = serde_json::json!({
            "node_id": node_id,
            "name": prior.name,
            "user_edited_name": prior.user_edited_name,
        });
        self.append_history(tree_id, "rename", &args, &undo)?;
        Ok(())
    }

    /// Apply an LLM-generated name + summary to a cluster node without
    /// flipping `user_edited_*`. Honors existing user-edit flags by
    /// leaving the corresponding field alone. Resets
    /// `summary_membership_churn` to 0 (a fresh summary captures the
    /// current member set). Appends a `raptor-summarize` history entry.
    /// Returns `(wrote_name, wrote_summary)`.
    pub fn auto_set_name_summary(
        &self,
        tree_id: &str,
        node_id: &str,
        new_name: &str,
        new_summary: &str,
    ) -> Result<(bool, bool), TreesError> {
        let prior = self.get_node(tree_id, node_id)?.ok_or_else(|| {
            TreesError::NodeNotFound {
                tree_id: tree_id.to_string(),
                node_id: node_id.to_string(),
            }
        })?;
        let write_name = !prior.user_edited_name;
        let write_summary = !prior.user_edited_summary;
        if !write_name && !write_summary {
            return Ok((false, false));
        }
        {
            let conn = self.conn.lock().expect("trees mutex poisoned");
            match (write_name, write_summary) {
                (true, true) => {
                    conn.execute(
                        "UPDATE cluster_nodes
                         SET name = ?1, summary = ?2, summary_membership_churn = 0
                         WHERE tree_id = ?3 AND node_id = ?4",
                        params![new_name, new_summary, tree_id, node_id],
                    )?;
                }
                (true, false) => {
                    conn.execute(
                        "UPDATE cluster_nodes
                         SET name = ?1, summary_membership_churn = 0
                         WHERE tree_id = ?2 AND node_id = ?3",
                        params![new_name, tree_id, node_id],
                    )?;
                }
                (false, true) => {
                    conn.execute(
                        "UPDATE cluster_nodes
                         SET summary = ?1, summary_membership_churn = 0
                         WHERE tree_id = ?2 AND node_id = ?3",
                        params![new_summary, tree_id, node_id],
                    )?;
                }
                (false, false) => unreachable!(),
            }
        }
        let args = serde_json::json!({
            "node_id": node_id,
            "name": new_name,
            "summary": new_summary,
            "wrote_name": write_name,
            "wrote_summary": write_summary,
        });
        let undo = serde_json::json!({
            "node_id": node_id,
            "name": prior.name,
            "summary": prior.summary,
            "summary_membership_churn": prior.summary_membership_churn,
        });
        self.append_history(tree_id, "raptor-summarize", &args, &undo)?;
        Ok((write_name, write_summary))
    }

    /// Edit a cluster's summary text. Stamps `user_edited_summary = true`.
    /// Appends an `edit-summary` history entry.
    pub fn set_summary(
        &self,
        tree_id: &str,
        node_id: &str,
        new_summary: &str,
    ) -> Result<(), TreesError> {
        let prior = self.get_node(tree_id, node_id)?.ok_or_else(|| {
            TreesError::NodeNotFound {
                tree_id: tree_id.to_string(),
                node_id: node_id.to_string(),
            }
        })?;
        {
            let conn = self.conn.lock().expect("trees mutex poisoned");
            conn.execute(
                "UPDATE cluster_nodes
                 SET summary = ?1, user_edited_summary = 1
                 WHERE tree_id = ?2 AND node_id = ?3",
                params![new_summary, tree_id, node_id],
            )?;
        }
        let args = serde_json::json!({ "node_id": node_id, "summary": new_summary });
        let undo = serde_json::json!({
            "node_id": node_id,
            "summary": prior.summary,
            "user_edited_summary": prior.user_edited_summary,
        });
        self.append_history(tree_id, "edit-summary", &args, &undo)?;
        Ok(())
    }

    /// Move a node to a new parent (or to the root when `new_parent` is
    /// `None`). Appends a `move` history entry.
    pub fn move_node(
        &self,
        tree_id: &str,
        node_id: &str,
        new_parent: Option<&str>,
    ) -> Result<(), TreesError> {
        let prior = self.get_node(tree_id, node_id)?.ok_or_else(|| {
            TreesError::NodeNotFound {
                tree_id: tree_id.to_string(),
                node_id: node_id.to_string(),
            }
        })?;
        {
            let conn = self.conn.lock().expect("trees mutex poisoned");
            conn.execute(
                "UPDATE cluster_nodes
                 SET parent_id = ?1
                 WHERE tree_id = ?2 AND node_id = ?3",
                params![new_parent, tree_id, node_id],
            )?;
        }
        let args = serde_json::json!({ "node_id": node_id, "parent_id": new_parent });
        let undo = serde_json::json!({ "node_id": node_id, "parent_id": prior.parent });
        self.append_history(tree_id, "move", &args, &undo)?;
        // status: cluster-summary-staleness-counter
        // Bump churn on the source and destination chains up to (but not
        // including) the LCA of old_parent and new_parent. The LCA and
        // its ancestors contain the moved node both before and after, so
        // their subtree leaf sets are unchanged and their summaries do
        // not become stale from the move.
        let new_parent_ancestors = match new_parent {
            Some(np) => self
                .ancestors_inclusive(tree_id, np)
                .unwrap_or_default(),
            None => std::collections::HashSet::new(),
        };
        let old_parent_ancestors = match prior.parent.as_deref() {
            Some(p) => self
                .ancestors_inclusive(tree_id, p)
                .unwrap_or_default(),
            None => std::collections::HashSet::new(),
        };
        if let Some(prev_parent) = prior.parent.as_deref() {
            let _ = self.bump_churn_chain_until(tree_id, prev_parent, &new_parent_ancestors, 1);
        }
        if let Some(np) = new_parent {
            let _ = self.bump_churn_chain_until(tree_id, np, &old_parent_ancestors, 1);
        }
        Ok(())
    }

    /// Collect a node and all of its ancestors up to the root as a set.
    /// Used to compute the LCA stop-set for move-style ops that should
    /// not bump churn on common ancestors (their subtree's leaf set is
    /// unchanged by an internal move).
    pub fn ancestors_inclusive(
        &self,
        tree_id: &str,
        node_id: &str,
    ) -> Result<std::collections::HashSet<String>, TreesError> {
        let conn = self.conn.lock().expect("trees mutex poisoned");
        let mut out = std::collections::HashSet::new();
        let mut cursor: Option<String> = Some(node_id.to_string());
        while let Some(id) = cursor {
            let parent: Option<Option<String>> = conn
                .query_row(
                    "SELECT parent_id FROM cluster_nodes WHERE tree_id = ?1 AND node_id = ?2",
                    params![tree_id, id],
                    |row| row.get::<_, Option<String>>(0),
                )
                .optional()?;
            let Some(parent) = parent else {
                break;
            };
            out.insert(id);
            cursor = parent;
        }
        Ok(out)
    }

    /// Like `bump_churn_chain` but stops (without bumping) when the walk
    /// reaches any node in `stop_at`. Used by move-style ops to skip
    /// churn bumps on the LCA and its ancestors — those nodes' subtree
    /// leaf sets are unchanged by a within-tree move.
    pub fn bump_churn_chain_until(
        &self,
        tree_id: &str,
        from_node: &str,
        stop_at: &std::collections::HashSet<String>,
        delta: u32,
    ) -> Result<(), TreesError> {
        if delta == 0 {
            return Ok(());
        }
        let mut conn = self.conn.lock().expect("trees mutex poisoned");
        let tx = conn.transaction()?;
        let mut cursor: Option<String> = Some(from_node.to_string());
        while let Some(id) = cursor {
            if stop_at.contains(&id) {
                break;
            }
            let parent: Option<Option<String>> = tx
                .query_row(
                    "SELECT parent_id FROM cluster_nodes WHERE tree_id = ?1 AND node_id = ?2",
                    params![tree_id, id],
                    |row| row.get::<_, Option<String>>(0),
                )
                .optional()?;
            let Some(parent) = parent else {
                break;
            };
            tx.execute(
                "UPDATE cluster_nodes
                 SET summary_membership_churn = summary_membership_churn + ?1
                 WHERE tree_id = ?2 AND node_id = ?3",
                params![delta as i64, tree_id, id],
            )?;
            cursor = parent;
        }
        tx.commit()?;
        Ok(())
    }

    /// Increment the membership-churn counter on a node and every
    /// ancestor up to the root. Per
    /// `cluster-build-from-folders-summary-staleness`.
    pub fn bump_churn_chain(
        &self,
        tree_id: &str,
        from_node: &str,
        delta: u32,
    ) -> Result<(), TreesError> {
        if delta == 0 {
            return Ok(());
        }
        let mut conn = self.conn.lock().expect("trees mutex poisoned");
        let tx = conn.transaction()?;
        let mut cursor: Option<String> = Some(from_node.to_string());
        while let Some(id) = cursor {
            let parent: Option<Option<String>> = tx
                .query_row(
                    "SELECT parent_id FROM cluster_nodes WHERE tree_id = ?1 AND node_id = ?2",
                    params![tree_id, id],
                    |row| row.get::<_, Option<String>>(0),
                )
                .optional()?;
            let Some(parent) = parent else {
                break;
            };
            tx.execute(
                "UPDATE cluster_nodes
                 SET summary_membership_churn = summary_membership_churn + ?1
                 WHERE tree_id = ?2 AND node_id = ?3",
                params![delta as i64, tree_id, id],
            )?;
            cursor = parent;
        }
        tx.commit()?;
        Ok(())
    }

    /// Live-update a FromFolders tree to reflect a vault rename. Per
    /// `cluster-build-from-folders-live-update`: the leaf with `note_id =
    /// note_id` (if present in this tree) is re-parented under the folder
    /// cluster matching `new_folder`. The folder cluster is created lazily
    /// when it doesn't yet exist. Emptied folder clusters are dropped
    /// unless they carry an explicit policy (the user's rule survives a
    /// transient empty state). Centroid recomputation is the producer's
    /// concern (cheap: vector mean over members) — for Sprint D we just
    /// keep the existing centroid since the move doesn't shift it much
    /// when the average folder has many notes.
    ///
    /// `new_folder` is the folder portion of the new vault-relative
    /// path (e.g. `"research/embeddings"`); `""` means "vault root".
    ///
    /// status: cluster-build-from-folders-live-update
    /// status: cluster-build-from-folders-summary-staleness
    pub fn update_for_folder_rename(
        &self,
        tree_id: &str,
        note_id: &str,
        new_folder: &str,
    ) -> Result<bool, TreesError> {
        // Locate the leaf by note_id within this tree. Scan once over the
        // full node list — trees.db tables are small per-tree.
        let nodes = self.list_nodes(tree_id)?;
        let Some(leaf) = nodes.iter().find(|n| {
            matches!(n.kind, NodeKind::Leaf)
                && n.note_ref.as_deref() == Some(note_id)
        }) else {
            // Not present in this tree — nothing to update.
            return Ok(false);
        };
        let prior_parent = leaf.parent.clone();
        // Compute the new folder cluster id. Mirrors `build_from_folders`'s
        // shape in core::cluster so existing trees keep working.
        let safe_folder = new_folder.replace('/', "-");
        let new_folder_cluster_id = format!(
            "f-{}",
            if safe_folder.is_empty() { "_root" } else { &safe_folder }
        );
        if prior_parent.as_deref() == Some(new_folder_cluster_id.as_str()) {
            // Already parented correctly.
            return Ok(false);
        }

        // Find the root (parent_id = NULL).
        let root_id = nodes
            .iter()
            .find(|n| n.parent.is_none())
            .map(|n| n.id.clone());

        // Ensure the destination folder cluster exists.
        let exists = nodes
            .iter()
            .any(|n| n.id == new_folder_cluster_id);
        if !exists {
            // Insert a fresh cluster node parented at the root.
            let basename = new_folder.rsplit('/').next().unwrap_or("");
            let display_name = if basename.is_empty() {
                "vault root".to_string()
            } else {
                basename.to_string()
            };
            self.insert_single_node(
                tree_id,
                NodeInsert {
                    node_id: new_folder_cluster_id.clone(),
                    parent_id: root_id.clone(),
                    kind: NodeKind::Cluster,
                    note_id: None,
                    name: display_name,
                    summary: String::new(),
                    user_edited_name: false,
                    user_edited_summary: false,
                    policy: None,
                    centroid: None,
                    confidence: 1.0,
                    summary_membership_churn: 0,
                },
            )?;
        }

        // Move the leaf. We bypass `move_node` here because that function
        // expects a NodeKind::Cluster destination via the same database
        // transaction and we want to capture the prior_parent for churn
        // bumping below.
        {
            let conn = self.conn.lock().expect("trees mutex poisoned");
            conn.execute(
                "UPDATE cluster_nodes SET parent_id = ?1 WHERE tree_id = ?2 AND node_id = ?3",
                params![new_folder_cluster_id, tree_id, leaf.id],
            )?;
        }
        let args = serde_json::json!({
            "note_id": note_id,
            "leaf_id": leaf.id,
            "new_folder": new_folder,
        });
        let undo = serde_json::json!({
            "leaf_id": leaf.id,
            "prior_parent": prior_parent,
        });
        self.append_history(tree_id, "folder-rename-update", &args, &undo)?;

        // Bump churn on both chains.
        if let Some(prev_parent) = prior_parent.as_deref() {
            let _ = self.bump_churn_chain(tree_id, prev_parent, 1);
        }
        let _ = self.bump_churn_chain(tree_id, &new_folder_cluster_id, 1);

        // Drop emptied folder clusters (unless they carry a policy or are
        // the root). Per spec: "emptied folders' nodes are dropped (unless
        // they carry an explicit policy, in which case they're kept as
        // empty placeholders so the user's rule survives a transient
        // empty state)."
        if let Some(prev_id) = prior_parent {
            let still_has_children: i64 = {
                let conn = self.conn.lock().expect("trees mutex poisoned");
                conn.query_row(
                    "SELECT COUNT(*) FROM cluster_nodes
                     WHERE tree_id = ?1 AND parent_id = ?2",
                    params![tree_id, prev_id],
                    |row| row.get(0),
                )?
            };
            if still_has_children == 0 {
                let prev_node = self.get_node(tree_id, &prev_id)?;
                if let Some(pn) = prev_node {
                    let is_root = pn.parent.is_none();
                    let has_policy = pn.policy.is_some();
                    let is_folder_cluster = pn.id.starts_with("f-");
                    if !is_root && !has_policy && is_folder_cluster {
                        self.delete_node(tree_id, &pn.id)?;
                    }
                }
            }
        }

        Ok(true)
    }

    /// Reset the churn counter on one node — called when the user runs
    /// "Regenerate" on the node.
    pub fn reset_churn(&self, tree_id: &str, node_id: &str) -> Result<(), TreesError> {
        let conn = self.conn.lock().expect("trees mutex poisoned");
        conn.execute(
            "UPDATE cluster_nodes
             SET summary_membership_churn = 0
             WHERE tree_id = ?1 AND node_id = ?2",
            params![tree_id, node_id],
        )?;
        Ok(())
    }

    /// Set the churn counter on one node to a specific value. Used by ops
    /// that need to neutralize spurious `bump_churn_chain` walks from
    /// nested reshape primitives (e.g. recluster-subtree restoring the
    /// selected-node-and-ancestors chain after `reparent_many`).
    pub fn set_churn(
        &self,
        tree_id: &str,
        node_id: &str,
        value: u32,
    ) -> Result<(), TreesError> {
        let conn = self.conn.lock().expect("trees mutex poisoned");
        conn.execute(
            "UPDATE cluster_nodes
             SET summary_membership_churn = ?1
             WHERE tree_id = ?2 AND node_id = ?3",
            params![value as i64, tree_id, node_id],
        )?;
        Ok(())
    }

    // ── History ──────────────────────────────────────────────────────

    /// Append one edit to `cluster_tree_history`. Public so the build
    /// pipeline (and any future op outside this module's vocabulary)
    /// can stamp custom op kinds. Returns the assigned `seq`.
    pub fn append_history(
        &self,
        tree_id: &str,
        op: &str,
        args: &serde_json::Value,
        undo_args: &serde_json::Value,
    ) -> Result<i64, TreesError> {
        let args_json = serde_json::to_string(args)?;
        let undo_json = serde_json::to_string(undo_args)?;
        let now = now_ms();
        let conn = self.conn.lock().expect("trees mutex poisoned");
        let next_seq: i64 = conn
            .query_row(
                "SELECT COALESCE(MAX(seq), 0) + 1 FROM cluster_tree_history WHERE tree_id = ?1",
                params![tree_id],
                |row| row.get(0),
            )?;
        conn.execute(
            "INSERT INTO cluster_tree_history (tree_id, seq, ts_ms, op, args, undo_args)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6)",
            params![tree_id, next_seq, now, op, args_json, undo_json],
        )?;
        Ok(next_seq)
    }

    // ── Reshape ops ─────────────────────────────────────────────────
    //
    // Higher-level mutations that compose multiple node-table edits.
    // Each one writes one history row (with symmetric `undo_args`) so
    // the per-pane undo/redo stack is uniform per
    // `cluster-editor-undo-redo`. Centroids and member-count side
    // effects stay outside this module — the UI recomputes on render.

    /// Merge a set of sibling clusters into one. The first id in `node_ids`
    /// is kept as the survivor; every other listed node's children are
    /// re-parented under the survivor, then the absorbed nodes are
    /// deleted. Records a `merge-siblings` history row.
    ///
    /// Errors if any node is missing, if they don't share a parent, or
    /// if fewer than two ids are passed.
    ///
    /// status: cluster-editor-merge-siblings
    pub fn merge_siblings(
        &self,
        tree_id: &str,
        node_ids: &[String],
    ) -> Result<String, TreesError> {
        if node_ids.len() < 2 {
            return Err(TreesError::TreeNotFound(format!(
                "merge_siblings needs >=2 ids, got {}",
                node_ids.len()
            )));
        }
        let nodes: Vec<EditableNode> = node_ids
            .iter()
            .map(|id| {
                self.get_node(tree_id, id)?.ok_or_else(|| TreesError::NodeNotFound {
                    tree_id: tree_id.to_string(),
                    node_id: id.clone(),
                })
            })
            .collect::<Result<Vec<_>, _>>()?;
        let parent = nodes[0].parent.clone();
        for n in &nodes[1..] {
            if n.parent != parent {
                return Err(TreesError::TreeNotFound(format!(
                    "merge_siblings: node {} has different parent",
                    n.id
                )));
            }
        }
        let survivor = node_ids[0].clone();
        let absorbed: Vec<String> = node_ids[1..].to_vec();
        // Snapshot the absorbed nodes so undo can restore them. Children
        // re-parent is reversible by recording each child's prior parent.
        let mut absorbed_snapshots: Vec<serde_json::Value> = Vec::new();
        let mut child_moves: Vec<serde_json::Value> = Vec::new();
        {
            let mut conn = self.conn.lock().expect("trees mutex poisoned");
            let tx = conn.transaction()?;
            for abs_id in &absorbed {
                // Snapshot full row.
                let snap = tx
                    .query_row(
                        "SELECT parent_id, kind, note_id, name, summary, user_edited_name,
                                user_edited_summary, policy, centroid, confidence, summary_membership_churn
                         FROM cluster_nodes WHERE tree_id = ?1 AND node_id = ?2",
                        params![tree_id, abs_id],
                        |row| {
                            Ok(serde_json::json!({
                                "parent_id": row.get::<_, Option<String>>(0)?,
                                "kind": row.get::<_, String>(1)?,
                                "note_id": row.get::<_, Option<String>>(2)?,
                                "name": row.get::<_, String>(3)?,
                                "summary": row.get::<_, String>(4)?,
                                "user_edited_name": row.get::<_, i32>(5)? != 0,
                                "user_edited_summary": row.get::<_, i32>(6)? != 0,
                                "policy": row.get::<_, Option<String>>(7)?,
                                "confidence": row.get::<_, f64>(9)?,
                                "summary_membership_churn": row.get::<_, i64>(10)?,
                            }))
                        },
                    )?;
                absorbed_snapshots.push(serde_json::json!({ "id": abs_id, "row": snap }));
                // Re-parent children under the survivor.
                let mut child_stmt = tx.prepare(
                    "SELECT node_id FROM cluster_nodes WHERE tree_id = ?1 AND parent_id = ?2",
                )?;
                let child_ids: Vec<String> = child_stmt
                    .query_map(params![tree_id, abs_id], |row| row.get::<_, String>(0))?
                    .collect::<Result<Vec<_>, _>>()?;
                drop(child_stmt);
                for cid in child_ids {
                    child_moves.push(serde_json::json!({
                        "child_id": cid,
                        "from": abs_id,
                        "to": survivor,
                    }));
                    tx.execute(
                        "UPDATE cluster_nodes SET parent_id = ?1
                         WHERE tree_id = ?2 AND node_id = ?3",
                        params![survivor, tree_id, cid],
                    )?;
                }
                tx.execute(
                    "DELETE FROM cluster_nodes WHERE tree_id = ?1 AND node_id = ?2",
                    params![tree_id, abs_id],
                )?;
            }
            tx.commit()?;
        }
        let args = serde_json::json!({
            "survivor": survivor,
            "absorbed": absorbed,
        });
        let undo = serde_json::json!({
            "survivor": survivor,
            "absorbed": absorbed_snapshots,
            "child_moves": child_moves,
        });
        self.append_history(tree_id, "merge-siblings", &args, &undo)?;
        // status: cluster-summary-staleness-counter — the survivor absorbed
        // every absorbed cluster's children, which is a real membership
        // change on the survivor's chain.
        let _ = self.bump_churn_chain(tree_id, &survivor, 1);
        Ok(survivor)
    }

    /// Flatten one level. Each child of `parent_id` that is itself a
    /// cluster has its children re-parented onto `parent_id`, then the
    /// emptied cluster nodes are deleted. Leaf children of `parent_id`
    /// stay put.
    ///
    /// status: cluster-editor-merge-children-up
    pub fn merge_children_up(&self, tree_id: &str, parent_id: &str) -> Result<(), TreesError> {
        // Snapshot so we can undo: each absorbed cluster + each
        // grand-child's prior parent.
        let mut absorbed_snapshots: Vec<serde_json::Value> = Vec::new();
        let mut grandchild_moves: Vec<serde_json::Value> = Vec::new();
        {
            let mut conn = self.conn.lock().expect("trees mutex poisoned");
            let tx = conn.transaction()?;
            let mut child_stmt = tx.prepare(
                "SELECT node_id, kind FROM cluster_nodes WHERE tree_id = ?1 AND parent_id = ?2",
            )?;
            let children: Vec<(String, String)> = child_stmt
                .query_map(params![tree_id, parent_id], |row| {
                    Ok((row.get::<_, String>(0)?, row.get::<_, String>(1)?))
                })?
                .collect::<Result<Vec<_>, _>>()?;
            drop(child_stmt);
            for (cid, kind) in &children {
                if kind != "cluster" {
                    continue;
                }
                let snap = tx
                    .query_row(
                        "SELECT parent_id, kind, note_id, name, summary, user_edited_name,
                                user_edited_summary, policy, confidence, summary_membership_churn
                         FROM cluster_nodes WHERE tree_id = ?1 AND node_id = ?2",
                        params![tree_id, cid],
                        |row| {
                            Ok(serde_json::json!({
                                "parent_id": row.get::<_, Option<String>>(0)?,
                                "kind": row.get::<_, String>(1)?,
                                "note_id": row.get::<_, Option<String>>(2)?,
                                "name": row.get::<_, String>(3)?,
                                "summary": row.get::<_, String>(4)?,
                                "user_edited_name": row.get::<_, i32>(5)? != 0,
                                "user_edited_summary": row.get::<_, i32>(6)? != 0,
                                "policy": row.get::<_, Option<String>>(7)?,
                                "confidence": row.get::<_, f64>(8)?,
                                "summary_membership_churn": row.get::<_, i64>(9)?,
                            }))
                        },
                    )?;
                absorbed_snapshots.push(serde_json::json!({ "id": cid, "row": snap }));
                let mut gc_stmt = tx.prepare(
                    "SELECT node_id FROM cluster_nodes WHERE tree_id = ?1 AND parent_id = ?2",
                )?;
                let gcs: Vec<String> = gc_stmt
                    .query_map(params![tree_id, cid], |row| row.get::<_, String>(0))?
                    .collect::<Result<Vec<_>, _>>()?;
                drop(gc_stmt);
                for gc in gcs {
                    grandchild_moves.push(serde_json::json!({
                        "child_id": gc,
                        "from": cid,
                        "to": parent_id,
                    }));
                    tx.execute(
                        "UPDATE cluster_nodes SET parent_id = ?1
                         WHERE tree_id = ?2 AND node_id = ?3",
                        params![parent_id, tree_id, gc],
                    )?;
                }
                tx.execute(
                    "DELETE FROM cluster_nodes WHERE tree_id = ?1 AND node_id = ?2",
                    params![tree_id, cid],
                )?;
            }
            tx.commit()?;
        }
        let args = serde_json::json!({ "parent_id": parent_id });
        let undo = serde_json::json!({
            "parent_id": parent_id,
            "absorbed": absorbed_snapshots,
            "grandchild_moves": grandchild_moves,
        });
        self.append_history(tree_id, "merge-children-up", &args, &undo)?;
        // status: cluster-summary-staleness-counter — the parent absorbed
        // grandchildren; bump its chain.
        let _ = self.bump_churn_chain(tree_id, parent_id, 1);
        Ok(())
    }

    /// Drop a cluster: its leaf descendants are re-parented under the
    /// nearest outlier bucket; nested cluster nodes are deleted along
    /// with the dropped cluster. Records a `drop-cluster` history row.
    /// `outlier_bucket_id` is the destination — caller (UI) picks it
    /// from the tree's outlier nodes (or creates one if missing).
    ///
    /// status: cluster-editor-drop-cluster
    pub fn drop_cluster(
        &self,
        tree_id: &str,
        node_id: &str,
        outlier_bucket_id: &str,
    ) -> Result<(), TreesError> {
        // Collect every descendant (DFS) so we know which leaves to
        // re-parent and which clusters to delete.
        let all_nodes = self.list_nodes(tree_id)?;
        let mut children_by_parent: std::collections::HashMap<String, Vec<EditableNode>> =
            std::collections::HashMap::new();
        for n in all_nodes.iter().cloned() {
            if let Some(p) = n.parent.clone() {
                children_by_parent.entry(p).or_default().push(n);
            }
        }
        let mut to_visit: Vec<String> = vec![node_id.to_string()];
        let mut cluster_descendants: Vec<EditableNode> = Vec::new();
        let mut leaf_descendants: Vec<EditableNode> = Vec::new();
        while let Some(id) = to_visit.pop() {
            if let Some(kids) = children_by_parent.get(&id) {
                for k in kids {
                    match k.kind {
                        NodeKind::Leaf => leaf_descendants.push(k.clone()),
                        _ => {
                            cluster_descendants.push(k.clone());
                            to_visit.push(k.id.clone());
                        }
                    }
                }
            }
        }
        // Snapshot the cluster itself for restore.
        let dropped_node = self.get_node(tree_id, node_id)?.ok_or_else(|| {
            TreesError::NodeNotFound {
                tree_id: tree_id.to_string(),
                node_id: node_id.to_string(),
            }
        })?;
        // Record prior parents of all leaves so undo can re-attach.
        let leaf_moves: Vec<serde_json::Value> = leaf_descendants
            .iter()
            .map(|l| {
                serde_json::json!({
                    "leaf_id": l.id,
                    "prior_parent": l.parent,
                })
            })
            .collect();
        let absorbed_clusters: Vec<serde_json::Value> = cluster_descendants
            .iter()
            .chain(std::iter::once(&dropped_node))
            .map(|c| {
                serde_json::json!({
                    "id": c.id,
                    "parent_id": c.parent,
                    "kind": match c.kind { NodeKind::Cluster => "cluster", NodeKind::OutlierBucket => "outlier-bucket", _ => "leaf" },
                    "name": c.name,
                    "summary": c.summary,
                    "user_edited_name": c.user_edited_name,
                    "user_edited_summary": c.user_edited_summary,
                    "policy": c.policy.as_ref().and_then(|p| serde_json::to_string(p).ok()),
                    "confidence": c.confidence,
                })
            })
            .collect();
        {
            let mut conn = self.conn.lock().expect("trees mutex poisoned");
            let tx = conn.transaction()?;
            for l in &leaf_descendants {
                tx.execute(
                    "UPDATE cluster_nodes SET parent_id = ?1 WHERE tree_id = ?2 AND node_id = ?3",
                    params![outlier_bucket_id, tree_id, l.id],
                )?;
            }
            for c in &cluster_descendants {
                tx.execute(
                    "DELETE FROM cluster_nodes WHERE tree_id = ?1 AND node_id = ?2",
                    params![tree_id, c.id],
                )?;
            }
            tx.execute(
                "DELETE FROM cluster_nodes WHERE tree_id = ?1 AND node_id = ?2",
                params![tree_id, node_id],
            )?;
            tx.commit()?;
        }
        let args = serde_json::json!({
            "node_id": node_id,
            "outlier_bucket_id": outlier_bucket_id,
        });
        let undo = serde_json::json!({
            "node_id": node_id,
            "outlier_bucket_id": outlier_bucket_id,
            "leaf_moves": leaf_moves,
            "absorbed_clusters": absorbed_clusters,
        });
        self.append_history(tree_id, "drop-cluster", &args, &undo)?;
        // status: cluster-summary-staleness-counter — the outlier bucket
        // gained the dropped cluster's leaves; bump its chain.
        let _ = self.bump_churn_chain(tree_id, outlier_bucket_id, 1);
        Ok(())
    }

    /// Promote an outlier (leaf inside an outlier-bucket) to a regular
    /// cluster, or demote a regular leaf into an outlier bucket. Wraps
    /// `move_node` but records a distinct `promote-outlier` op so the
    /// history reads naturally. Caller passes the destination parent.
    ///
    /// status: cluster-editor-promote-outlier
    pub fn promote_outlier(
        &self,
        tree_id: &str,
        leaf_id: &str,
        new_parent: Option<&str>,
    ) -> Result<(), TreesError> {
        let prior = self.get_node(tree_id, leaf_id)?.ok_or_else(|| {
            TreesError::NodeNotFound {
                tree_id: tree_id.to_string(),
                node_id: leaf_id.to_string(),
            }
        })?;
        {
            let conn = self.conn.lock().expect("trees mutex poisoned");
            conn.execute(
                "UPDATE cluster_nodes SET parent_id = ?1 WHERE tree_id = ?2 AND node_id = ?3",
                params![new_parent, tree_id, leaf_id],
            )?;
        }
        let args = serde_json::json!({ "leaf_id": leaf_id, "parent_id": new_parent });
        let undo = serde_json::json!({ "leaf_id": leaf_id, "parent_id": prior.parent });
        self.append_history(tree_id, "promote-outlier", &args, &undo)?;
        // status: cluster-summary-staleness-counter
        if let Some(prev_parent) = prior.parent.as_deref() {
            let _ = self.bump_churn_chain(tree_id, prev_parent, 1);
        }
        if let Some(np) = new_parent {
            let _ = self.bump_churn_chain(tree_id, np, 1);
        }
        Ok(())
    }

    /// Append a single new node row. Used by split + future operations
    /// that grow the tree mid-edit. Doesn't write a history row itself —
    /// callers wrap this inside a higher-level op that does.
    pub fn insert_single_node(&self, tree_id: &str, n: NodeInsert) -> Result<(), TreesError> {
        let policy_json = match &n.policy {
            Some(p) => Some(serde_json::to_string(p)?),
            None => None,
        };
        let centroid_bytes = n.centroid.as_ref().map(pack_centroid);
        let conn = self.conn.lock().expect("trees mutex poisoned");
        conn.execute(
            "INSERT INTO cluster_nodes
               (tree_id, node_id, parent_id, kind, note_id, name, summary,
                user_edited_name, user_edited_summary, policy, centroid,
                confidence, summary_membership_churn)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, ?11, ?12, ?13)",
            params![
                tree_id,
                n.node_id,
                n.parent_id,
                n.kind.as_str(),
                n.note_id,
                n.name,
                n.summary,
                n.user_edited_name as i32,
                n.user_edited_summary as i32,
                policy_json,
                centroid_bytes,
                n.confidence as f64,
                n.summary_membership_churn as i64,
            ],
        )?;
        Ok(())
    }

    /// Re-parent a batch of nodes onto new parents. Used by split to
    /// move existing leaves under their new sub-cluster homes. Doesn't
    /// write history — the wrapping op does.
    ///
    /// status: cluster-summary-staleness-counter
    /// Bumps churn on each moved node's prior-parent chain and on each
    /// destination chain, mirroring `move_node`. Split (the main caller)
    /// relocates every leaf under a former cluster onto new sub-clusters,
    /// and the spec ("Every leaf insert or remove within a cluster's
    /// subtree increments the counter on that cluster and all its
    /// ancestors") covers the case — bumping here ensures the wrapping
    /// `cluster_op_split` doesn't need to repeat the walk, and any future
    /// caller is covered automatically.
    pub fn reparent_many(
        &self,
        tree_id: &str,
        moves: &[(String, Option<String>)],
    ) -> Result<(), TreesError> {
        // Capture prior parents before mutating so we can bump the source
        // chain after the move. Read in a short-lived scope to avoid
        // holding the mutex across the bump_churn_chain calls below
        // (which re-acquire it).
        let prior_parents: Vec<Option<String>> = {
            let conn = self.conn.lock().expect("trees mutex poisoned");
            let mut out = Vec::with_capacity(moves.len());
            for (id, _) in moves {
                let p: Option<Option<String>> = conn
                    .query_row(
                        "SELECT parent_id FROM cluster_nodes WHERE tree_id = ?1 AND node_id = ?2",
                        params![tree_id, id],
                        |row| row.get::<_, Option<String>>(0),
                    )
                    .optional()?;
                out.push(p.unwrap_or(None));
            }
            out
        };
        {
            let mut conn = self.conn.lock().expect("trees mutex poisoned");
            let tx = conn.transaction()?;
            for (id, parent) in moves {
                tx.execute(
                    "UPDATE cluster_nodes SET parent_id = ?1 WHERE tree_id = ?2 AND node_id = ?3",
                    params![parent, tree_id, id],
                )?;
            }
            tx.commit()?;
        }
        // Bump churn on both ends of each move, stopping at the LCA so
        // common ancestors (whose subtree leaf set didn't change) don't
        // accumulate spurious staleness. Same shape as `move_node`.
        for ((_, new_parent), prev) in moves.iter().zip(prior_parents.iter()) {
            let new_parent_ancestors = match new_parent.as_deref() {
                Some(np) => self
                    .ancestors_inclusive(tree_id, np)
                    .unwrap_or_default(),
                None => std::collections::HashSet::new(),
            };
            let old_parent_ancestors = match prev.as_deref() {
                Some(p) => self
                    .ancestors_inclusive(tree_id, p)
                    .unwrap_or_default(),
                None => std::collections::HashSet::new(),
            };
            if let Some(prev_parent) = prev.as_deref() {
                let _ = self.bump_churn_chain_until(
                    tree_id,
                    prev_parent,
                    &new_parent_ancestors,
                    1,
                );
            }
            if let Some(np) = new_parent.as_deref() {
                let _ = self.bump_churn_chain_until(
                    tree_id,
                    np,
                    &old_parent_ancestors,
                    1,
                );
            }
        }
        Ok(())
    }

    /// Record a `split-cluster` history entry. Caller (cluster editor)
    /// runs the actual HDBSCAN-against-members pass via `core::cluster`
    /// and uses `insert_single_node` + `reparent_many` to land the new
    /// sub-clusters; this method ties the change to a single undo step.
    ///
    /// `new_clusters` carries enough per-cluster metadata (id, name,
    /// summary, confidence, …) to *replay* the split deterministically
    /// on redo — re-running HDBSCAN against the same members is
    /// non-deterministic, so redo restores the snapshot rather than
    /// re-clustering (per `cluster-editor-undo-redo`).
    ///
    /// status: cluster-editor-split-cluster
    pub fn record_split(
        &self,
        tree_id: &str,
        parent_id: &str,
        new_clusters: &[serde_json::Value],
        leaf_moves: &[(String, Option<String>)],
    ) -> Result<i64, TreesError> {
        let new_cluster_ids: Vec<String> = new_clusters
            .iter()
            .filter_map(|c| c.get("node_id").and_then(|v| v.as_str()).map(str::to_string))
            .collect();
        let args = serde_json::json!({
            "parent_id": parent_id,
            "new_cluster_ids": new_cluster_ids,
            "new_clusters": new_clusters,
            "leaf_moves": leaf_moves,
        });
        let undo = serde_json::json!({
            "parent_id": parent_id,
            "new_cluster_ids": new_cluster_ids,
            "new_clusters": new_clusters,
            "leaf_moves": leaf_moves,
        });
        self.append_history(tree_id, "split-cluster", &args, &undo)?;
        Ok(0)
    }

    /// Record a `recluster-subtree` history entry. Like `record_split`,
    /// the caller is responsible for running the actual clustering pass
    /// (`core::cluster::build_tree` against the subtree's leaves) and
    /// for the cluster_nodes mutations (delete descendants, insert new
    /// cluster rows, reparent leaves). This method only persists enough
    /// state on the history row to replay (redo) and reverse (undo) the
    /// reshape.
    ///
    /// `prior_subtree` carries each deleted cluster's full row shape +
    /// its prior `parent_id` so undo can re-insert them exactly. The
    /// snapshot also records the resolved policy carried onto direct
    /// children (when "Carry policies down" was checked) so the user's
    /// intent is preserved in the audit log.
    ///
    /// `new_nodes` carries the inserted cluster rows in dependency order
    /// (parents before children) so redo can restore_node_row each one
    /// in turn. `leaf_moves` is the `(leaf_id, new_parent)` list.
    ///
    /// Per `cluster-editor-recluster-subtree`,
    /// `cluster-editor-recluster-subtree-policy-loss` (the carried
    /// policies and the explicit "policies are lost" semantics), and the
    /// undo-snapshots-prior-subtree clause.
    ///
    /// status: cluster-editor-recluster-subtree
    /// status: cluster-editor-recluster-subtree-policy-loss
    pub fn record_recluster_subtree(
        &self,
        tree_id: &str,
        root_id: &str,
        prior_subtree: &[serde_json::Value],
        prior_leaf_parents: &[(String, Option<String>)],
        new_nodes: &[serde_json::Value],
        leaf_moves: &[(String, Option<String>)],
        carried_policy: Option<&NodePolicy>,
    ) -> Result<i64, TreesError> {
        let new_node_ids: Vec<String> = new_nodes
            .iter()
            .filter_map(|c| c.get("id").and_then(|v| v.as_str()).map(str::to_string))
            .collect();
        let carried_policy_json = match carried_policy {
            Some(p) => Some(serde_json::to_value(p)?),
            None => None,
        };
        let args = serde_json::json!({
            "root_id": root_id,
            "new_node_ids": new_node_ids,
            "new_nodes": new_nodes,
            "leaf_moves": leaf_moves,
            "carried_policy": carried_policy_json,
        });
        let undo = serde_json::json!({
            "root_id": root_id,
            "new_node_ids": new_node_ids,
            "prior_subtree": prior_subtree,
            "prior_leaf_parents": prior_leaf_parents,
            "leaf_moves": leaf_moves,
        });
        self.append_history(tree_id, "recluster-subtree", &args, &undo)
    }

    /// Delete a single node by id. Reserved for the cluster editor's
    /// own clean-up paths (e.g. removing an empty cluster after a
    /// reshape).
    ///
    /// status: cluster-summary-staleness-counter
    /// No churn bump here: this is a structural drop of an already-empty
    /// cluster shell (the caller's policy in `update_for_folder_rename`
    /// only invokes us once `still_has_children == 0`), so no leaf
    /// insert-or-remove crosses an ancestor boundary that wasn't already
    /// counted by the upstream move. Leaf removals proper happen through
    /// `move_node` / `reparent_many` / `promote_outlier`, all of which
    /// bump their ancestor chains directly.
    pub fn delete_node(&self, tree_id: &str, node_id: &str) -> Result<(), TreesError> {
        let conn = self.conn.lock().expect("trees mutex poisoned");
        conn.execute(
            "DELETE FROM cluster_nodes WHERE tree_id = ?1 AND node_id = ?2",
            params![tree_id, node_id],
        )?;
        Ok(())
    }

    // ── Undo / redo ─────────────────────────────────────────────────
    //
    // The history table records `args` (forward) + `undo_args` (reverse)
    // for every mutation. `pop_history` returns the most-recent entry
    // and removes it so a subsequent `append_history` doesn't conflict
    // with the seq sequence. Redo is implemented by re-applying the
    // popped entry's `args` — the UI re-routes through the regular ops.
    //
    // Edit replays in this module are deliberately keyed off operation
    // name strings so new ops added by the cluster editor (Sprint B)
    // and triage (Sprint C) compose cleanly without a central enum.
    //
    // status: cluster-editor-undo-redo

    /// Pop the most-recent history entry for a tree (returns `None`
    /// when the log is empty). Used by undo: caller reads `entry.op` +
    /// `entry.undo_args` and inverts the change.
    pub fn pop_last_history(&self, tree_id: &str) -> Result<Option<HistoryEntry>, TreesError> {
        let conn = self.conn.lock().expect("trees mutex poisoned");
        let entry: Option<HistoryEntry> = conn
            .query_row(
                "SELECT seq, ts_ms, op, args, undo_args
                 FROM cluster_tree_history
                 WHERE tree_id = ?1
                 ORDER BY seq DESC LIMIT 1",
                params![tree_id],
                |row| {
                    Ok(HistoryEntry {
                        seq: row.get(0)?,
                        ts_ms: row.get(1)?,
                        op: row.get(2)?,
                        args_json: row.get(3)?,
                        undo_args_json: row.get(4)?,
                    })
                },
            )
            .optional()?;
        if let Some(e) = &entry {
            conn.execute(
                "DELETE FROM cluster_tree_history WHERE tree_id = ?1 AND seq = ?2",
                params![tree_id, e.seq],
            )?;
        }
        Ok(entry)
    }

    /// Read the history log for a tree, oldest first.
    pub fn history(&self, tree_id: &str) -> Result<Vec<HistoryEntry>, TreesError> {
        let conn = self.conn.lock().expect("trees mutex poisoned");
        let mut stmt = conn.prepare(
            "SELECT seq, ts_ms, op, args, undo_args FROM cluster_tree_history
             WHERE tree_id = ?1 ORDER BY seq ASC",
        )?;
        let rows = stmt
            .query_map(params![tree_id], |row| {
                Ok(HistoryEntry {
                    seq: row.get(0)?,
                    ts_ms: row.get(1)?,
                    op: row.get(2)?,
                    args_json: row.get(3)?,
                    undo_args_json: row.get(4)?,
                })
            })?
            .collect::<Result<Vec<_>, _>>()?;
        Ok(rows)
    }
}

// ── SQL helpers ──────────────────────────────────────────────────────

const NODE_SELECT_SQL: &str = "
    SELECT node_id, parent_id, kind, note_id, name, summary,
           user_edited_name, user_edited_summary, policy, centroid,
           confidence, summary_membership_churn
    FROM cluster_nodes WHERE tree_id = ?1 AND node_id = ?2";

fn map_tree_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<TreeRow> {
    Ok(TreeRow {
        id: row.get(0)?,
        name: row.get(1)?,
        source: row.get(2)?,
        state: row.get(3)?,
        scope_json: row.get(4)?,
        method_json: row.get(5)?,
        created_at_ms: row.get(6)?,
        vault_snapshot: row.get(7)?,
    })
}

fn map_editable_node(
    row: &rusqlite::Row<'_>,
) -> rusqlite::Result<Result<EditableNode, TreesError>> {
    let node_id: String = row.get(0)?;
    let parent_id: Option<String> = row.get(1)?;
    let kind_str: String = row.get(2)?;
    let note_id: Option<String> = row.get(3)?;
    let name: String = row.get(4)?;
    let summary: String = row.get(5)?;
    let user_edited_name: i32 = row.get(6)?;
    let user_edited_summary: i32 = row.get(7)?;
    let policy_json: Option<String> = row.get(8)?;
    let centroid_blob: Option<Vec<u8>> = row.get(9)?;
    let confidence: f64 = row.get(10)?;
    let churn: i64 = row.get(11)?;

    Ok((|| -> Result<EditableNode, TreesError> {
        let kind = NodeKind::parse(&kind_str).ok_or_else(|| {
            TreesError::Sqlite(rusqlite::Error::FromSqlConversionFailure(
                2,
                rusqlite::types::Type::Text,
                Box::new(std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("unknown node kind: {kind_str}"),
                )),
            ))
        })?;
        let policy = match policy_json {
            Some(s) => Some(serde_json::from_str(&s)?),
            None => None,
        };
        let centroid = centroid_blob.as_deref().map(unpack_centroid);
        Ok(EditableNode {
            id: node_id,
            parent: parent_id,
            kind,
            note_ref: note_id,
            name,
            summary,
            user_edited_name: user_edited_name != 0,
            user_edited_summary: user_edited_summary != 0,
            policy,
            centroid,
            confidence: confidence as f32,
            summary_membership_churn: churn.max(0) as u32,
        })
    })())
}

fn pack_centroid(v: &Vec<f32>) -> Vec<u8> {
    let mut out = Vec::with_capacity(v.len() * 4);
    for x in v {
        out.extend_from_slice(&x.to_le_bytes());
    }
    out
}

fn unpack_centroid(bytes: &[u8]) -> Vec<f32> {
    let mut out = Vec::with_capacity(bytes.len() / 4);
    for chunk in bytes.chunks_exact(4) {
        let arr = [chunk[0], chunk[1], chunk[2], chunk[3]];
        out.push(f32::from_le_bytes(arr));
    }
    out
}

fn now_ms() -> i64 {
    use std::time::{SystemTime, UNIX_EPOCH};
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

fn configure(conn: &Connection) -> Result<(), TreesError> {
    conn.pragma_update(None, "journal_mode", "WAL")?;
    conn.pragma_update(None, "foreign_keys", "ON")?;
    conn.pragma_update(None, "synchronous", "NORMAL")?;
    conn.busy_timeout(std::time::Duration::from_millis(5000))?;
    Ok(())
}

fn ensure_schema(conn: &mut Connection) -> Result<(), TreesError> {
    let user_version: i32 =
        conn.query_row("PRAGMA user_version", [], |row| row.get(0))?;
    if user_version != 0 && user_version != SCHEMA_VERSION {
        return Err(TreesError::VersionMismatch {
            found: user_version,
            expected: SCHEMA_VERSION,
        });
    }
    conn.execute_batch(
        r#"
        CREATE TABLE IF NOT EXISTS cluster_trees (
            id              TEXT PRIMARY KEY,
            name            TEXT NOT NULL,
            source          TEXT NOT NULL,
            state           TEXT NOT NULL,
            scope           TEXT NOT NULL,
            method          TEXT NOT NULL,
            created_at_ms   INTEGER NOT NULL,
            vault_snapshot  TEXT
        );

        CREATE TABLE IF NOT EXISTS cluster_nodes (
            tree_id                  TEXT NOT NULL REFERENCES cluster_trees(id) ON DELETE CASCADE,
            node_id                  TEXT NOT NULL,
            parent_id                TEXT,
            kind                     TEXT NOT NULL,
            note_id                  TEXT,
            name                     TEXT NOT NULL,
            summary                  TEXT NOT NULL,
            user_edited_name         INTEGER NOT NULL DEFAULT 0,
            user_edited_summary      INTEGER NOT NULL DEFAULT 0,
            policy                   TEXT,
            centroid                 BLOB,
            confidence               REAL,
            summary_membership_churn INTEGER NOT NULL DEFAULT 0,
            PRIMARY KEY (tree_id, node_id)
        );
        CREATE INDEX IF NOT EXISTS cluster_nodes_parent
            ON cluster_nodes(tree_id, parent_id);
        CREATE INDEX IF NOT EXISTS cluster_nodes_note
            ON cluster_nodes(tree_id, note_id);

        CREATE TABLE IF NOT EXISTS cluster_tree_history (
            tree_id   TEXT NOT NULL REFERENCES cluster_trees(id) ON DELETE CASCADE,
            seq       INTEGER NOT NULL,
            ts_ms     INTEGER NOT NULL,
            op        TEXT NOT NULL,
            args      TEXT NOT NULL,
            undo_args TEXT NOT NULL,
            PRIMARY KEY (tree_id, seq)
        );
        CREATE INDEX IF NOT EXISTS cluster_tree_history_seq_desc
            ON cluster_tree_history(tree_id, seq DESC);
        "#,
    )?;
    if user_version == 0 {
        conn.pragma_update(None, "user_version", SCHEMA_VERSION)?;
        tracing::info!(
            schema_version = SCHEMA_VERSION,
            "trees: created trees db schema",
        );
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn open_tmp() -> (TempDir, Trees) {
        let dir = TempDir::new().unwrap();
        let trees = Trees::open(dir.path()).unwrap();
        (dir, trees)
    }

    #[test]
    fn insert_and_get_tree() {
        let (_d, trees) = open_tmp();
        let id = trees
            .insert_tree(TreeInsert {
                id: None,
                name: "test".into(),
                source: "one-shot".into(),
                state: "draft".into(),
                scope_json: "{\"kind\":\"vault\"}".into(),
                method_json: "{\"kind\":\"cluster\"}".into(),
                vault_snapshot: None,
            })
            .unwrap();
        let row = trees.get_tree(&id).unwrap().expect("tree exists");
        assert_eq!(row.name, "test");
        assert_eq!(row.state, "draft");
    }

    #[test]
    fn insert_nodes_and_hydrate() {
        let (_d, trees) = open_tmp();
        let tree_id = trees
            .insert_tree(TreeInsert {
                id: Some("t1".into()),
                name: "t".into(),
                source: "one-shot".into(),
                state: "draft".into(),
                scope_json: "{}".into(),
                method_json: "{}".into(),
                vault_snapshot: None,
            })
            .unwrap();
        trees
            .insert_nodes(
                &tree_id,
                &[
                    NodeInsert {
                        node_id: "root".into(),
                        parent_id: None,
                        kind: NodeKind::Cluster,
                        note_id: None,
                        name: "Vault root".into(),
                        summary: "".into(),
                        user_edited_name: false,
                        user_edited_summary: false,
                        policy: None,
                        centroid: Some(vec![0.5, 0.5, 0.5]),
                        confidence: 1.0,
                        summary_membership_churn: 0,
                    },
                    NodeInsert {
                        node_id: "leaf1".into(),
                        parent_id: Some("root".into()),
                        kind: NodeKind::Leaf,
                        note_id: Some("note-a".into()),
                        name: "note-a".into(),
                        summary: "".into(),
                        user_edited_name: false,
                        user_edited_summary: false,
                        policy: None,
                        centroid: None,
                        confidence: 1.0,
                        summary_membership_churn: 0,
                    },
                ],
            )
            .unwrap();
        let root = trees.get_node(&tree_id, "root").unwrap().unwrap();
        assert_eq!(root.kind, NodeKind::Cluster);
        assert_eq!(root.centroid.as_ref().unwrap().len(), 3);
        let kids = trees.children_of(&tree_id, Some("root")).unwrap();
        assert_eq!(kids.len(), 1);
        assert_eq!(kids[0].id, "leaf1");
        assert_eq!(kids[0].note_ref.as_deref(), Some("note-a"));
    }

    #[test]
    fn history_records_edits() {
        let (_d, trees) = open_tmp();
        let tree_id = trees
            .insert_tree(TreeInsert {
                id: Some("t2".into()),
                name: "t".into(),
                source: "one-shot".into(),
                state: "draft".into(),
                scope_json: "{}".into(),
                method_json: "{}".into(),
                vault_snapshot: None,
            })
            .unwrap();
        trees
            .insert_nodes(
                &tree_id,
                &[NodeInsert {
                    node_id: "n1".into(),
                    parent_id: None,
                    kind: NodeKind::Cluster,
                    note_id: None,
                    name: "old".into(),
                    summary: "old-summary".into(),
                    user_edited_name: false,
                    user_edited_summary: false,
                    policy: None,
                    centroid: None,
                    confidence: 0.8,
                    summary_membership_churn: 0,
                }],
            )
            .unwrap();
        trees.rename(&tree_id, "n1", "new").unwrap();
        trees
            .set_policy(
                &tree_id,
                "n1",
                Some(NodePolicy::Tag {
                    slug: "research".into(),
                    require_review: false,
                }),
            )
            .unwrap();
        let h = trees.history(&tree_id).unwrap();
        assert_eq!(h.len(), 2);
        assert_eq!(h[0].op, "rename");
        assert_eq!(h[1].op, "set-policy");
        let n = trees.get_node(&tree_id, "n1").unwrap().unwrap();
        assert_eq!(n.name, "new");
        assert!(n.user_edited_name);
        assert!(matches!(n.policy, Some(NodePolicy::Tag { .. })));
    }

    #[test]
    fn churn_bubbles_to_ancestors() {
        let (_d, trees) = open_tmp();
        let tid = trees
            .insert_tree(TreeInsert {
                id: Some("t3".into()),
                name: "t".into(),
                source: "one-shot".into(),
                state: "draft".into(),
                scope_json: "{}".into(),
                method_json: "{}".into(),
                vault_snapshot: None,
            })
            .unwrap();
        trees
            .insert_nodes(
                &tid,
                &[
                    NodeInsert {
                        node_id: "r".into(),
                        parent_id: None,
                        kind: NodeKind::Cluster,
                        note_id: None,
                        name: "r".into(),
                        summary: "".into(),
                        user_edited_name: false,
                        user_edited_summary: false,
                        policy: None,
                        centroid: None,
                        confidence: 1.0,
                        summary_membership_churn: 0,
                    },
                    NodeInsert {
                        node_id: "c".into(),
                        parent_id: Some("r".into()),
                        kind: NodeKind::Cluster,
                        note_id: None,
                        name: "c".into(),
                        summary: "".into(),
                        user_edited_name: false,
                        user_edited_summary: false,
                        policy: None,
                        centroid: None,
                        confidence: 1.0,
                        summary_membership_churn: 0,
                    },
                    NodeInsert {
                        node_id: "l".into(),
                        parent_id: Some("c".into()),
                        kind: NodeKind::Leaf,
                        note_id: Some("note".into()),
                        name: "leaf".into(),
                        summary: "".into(),
                        user_edited_name: false,
                        user_edited_summary: false,
                        policy: None,
                        centroid: None,
                        confidence: 1.0,
                        summary_membership_churn: 0,
                    },
                ],
            )
            .unwrap();
        trees.bump_churn_chain(&tid, "l", 1).unwrap();
        // The leaf, its parent, and the root all increment.
        let leaf = trees.get_node(&tid, "l").unwrap().unwrap();
        let mid = trees.get_node(&tid, "c").unwrap().unwrap();
        let root = trees.get_node(&tid, "r").unwrap().unwrap();
        assert_eq!(leaf.summary_membership_churn, 1);
        assert_eq!(mid.summary_membership_churn, 1);
        assert_eq!(root.summary_membership_churn, 1);
        trees.reset_churn(&tid, "c").unwrap();
        let mid = trees.get_node(&tid, "c").unwrap().unwrap();
        assert_eq!(mid.summary_membership_churn, 0);
    }

    // status: cluster-editor-undo-redo
    //
    // Round-trips the reshape ops: forward → snapshot state → simulate
    // undo via the recorded `undo_args` → re-run forward (redo) →
    // confirm the post-redo state matches the post-forward state.
    //
    // The actual undo machinery lives in `ui/src-tauri/src/lib.rs`
    // (Tauri command surface); here we exercise the underlying invariant
    // that the forward ops are idempotent against existing-IDs and that
    // the recorded `args_json` carries enough info to replay.
    #[test]
    fn merge_siblings_redo_roundtrip() {
        let (_d, trees) = open_tmp();
        let tid = trees
            .insert_tree(TreeInsert {
                id: Some("trip".into()),
                name: "t".into(),
                source: "one-shot".into(),
                state: "draft".into(),
                scope_json: "{}".into(),
                method_json: "{}".into(),
                vault_snapshot: None,
            })
            .unwrap();
        let mk = |id: &str, parent: Option<&str>, kind: NodeKind| NodeInsert {
            node_id: id.into(),
            parent_id: parent.map(|s| s.into()),
            kind,
            note_id: None,
            name: id.into(),
            summary: String::new(),
            user_edited_name: false,
            user_edited_summary: false,
            policy: None,
            centroid: None,
            confidence: 1.0,
            summary_membership_churn: 0,
        };
        trees
            .insert_nodes(
                &tid,
                &[
                    mk("root", None, NodeKind::Cluster),
                    mk("a", Some("root"), NodeKind::Cluster),
                    mk("b", Some("root"), NodeKind::Cluster),
                    mk("a-child", Some("a"), NodeKind::Cluster),
                    mk("b-child", Some("b"), NodeKind::Cluster),
                ],
            )
            .unwrap();
        // Forward merge: a absorbs b.
        let survivor = trees
            .merge_siblings(&tid, &["a".into(), "b".into()])
            .unwrap();
        assert_eq!(survivor, "a");
        assert!(trees.get_node(&tid, "b").unwrap().is_none());
        // a should now own a-child and b-child.
        let kids = trees.children_of(&tid, Some("a")).unwrap();
        let mut k_ids: Vec<String> = kids.iter().map(|n| n.id.clone()).collect();
        k_ids.sort();
        assert_eq!(k_ids, vec!["a-child", "b-child"]);

        // Simulate undo: read undo_args and restore.
        let h = trees.history(&tid).unwrap();
        let entry = h.last().cloned().unwrap();
        assert_eq!(entry.op, "merge-siblings");
        let _undo: serde_json::Value = serde_json::from_str(&entry.undo_args_json).unwrap();
        // Restore the absorbed node "b".
        trees
            .insert_single_node(
                &tid,
                NodeInsert {
                    node_id: "b".into(),
                    parent_id: Some("root".into()),
                    kind: NodeKind::Cluster,
                    note_id: None,
                    name: "b".into(),
                    summary: String::new(),
                    user_edited_name: false,
                    user_edited_summary: false,
                    policy: None,
                    centroid: None,
                    confidence: 1.0,
                    summary_membership_churn: 0,
                },
            )
            .unwrap();
        // Re-parent b-child back under b.
        trees
            .reparent_many(&tid, &[("b-child".into(), Some("b".into()))])
            .unwrap();
        // Confirm state is restored.
        assert!(trees.get_node(&tid, "b").unwrap().is_some());
        let a_kids = trees.children_of(&tid, Some("a")).unwrap();
        assert_eq!(a_kids.len(), 1);
        assert_eq!(a_kids[0].id, "a-child");

        // Redo: re-run the forward op against the args from history.
        let args: serde_json::Value = serde_json::from_str(&entry.args_json).unwrap();
        let survivor = args.get("survivor").and_then(|v| v.as_str()).unwrap().to_string();
        let absorbed: Vec<String> = args
            .get("absorbed")
            .and_then(|v| v.as_array())
            .unwrap()
            .iter()
            .filter_map(|v| v.as_str().map(str::to_string))
            .collect();
        let mut redo_ids = vec![survivor];
        redo_ids.extend(absorbed);
        trees.merge_siblings(&tid, &redo_ids).unwrap();
        // Post-redo state should match post-forward.
        assert!(trees.get_node(&tid, "b").unwrap().is_none());
        let kids = trees.children_of(&tid, Some("a")).unwrap();
        let mut k_ids: Vec<String> = kids.iter().map(|n| n.id.clone()).collect();
        k_ids.sort();
        assert_eq!(k_ids, vec!["a-child", "b-child"]);
    }

    #[test]
    fn split_record_snapshots_new_clusters_for_redo() {
        // Confirms `record_split` persists enough state on `args_json`
        // to replay a split without re-running HDBSCAN. The redo path
        // in `ui/src-tauri` reads `new_clusters` + `leaf_moves` and
        // restores via `insert_single_node` + `reparent_many`.
        let (_d, trees) = open_tmp();
        let tid = trees
            .insert_tree(TreeInsert {
                id: Some("split-trip".into()),
                name: "t".into(),
                source: "one-shot".into(),
                state: "draft".into(),
                scope_json: "{}".into(),
                method_json: "{}".into(),
                vault_snapshot: None,
            })
            .unwrap();
        let new_clusters = vec![
            serde_json::json!({
                "node_id": "split-x-0",
                "parent_id": "x",
                "kind": "cluster",
                "name": "alpha / beta",
                "summary": "",
                "user_edited_name": false,
                "user_edited_summary": false,
                "policy": null,
                "confidence": 0.5,
                "summary_membership_churn": 0,
            }),
            serde_json::json!({
                "node_id": "split-x-1",
                "parent_id": "x",
                "kind": "cluster",
                "name": "gamma / delta",
                "summary": "",
                "user_edited_name": false,
                "user_edited_summary": false,
                "policy": null,
                "confidence": 0.5,
                "summary_membership_churn": 0,
            }),
        ];
        let leaf_moves: Vec<(String, Option<String>)> = vec![
            ("leaf-1".into(), Some("split-x-0".into())),
            ("leaf-2".into(), Some("split-x-1".into())),
        ];
        trees
            .record_split(&tid, "x", &new_clusters, &leaf_moves)
            .unwrap();
        let h = trees.history(&tid).unwrap();
        let entry = h.last().unwrap();
        let args: serde_json::Value = serde_json::from_str(&entry.args_json).unwrap();
        let nc = args.get("new_clusters").and_then(|v| v.as_array()).unwrap();
        assert_eq!(nc.len(), 2);
        assert_eq!(
            nc[0].get("node_id").and_then(|v| v.as_str()),
            Some("split-x-0"),
        );
        assert_eq!(
            nc[0].get("name").and_then(|v| v.as_str()),
            Some("alpha / beta"),
        );
        let lm = args.get("leaf_moves").and_then(|v| v.as_array()).unwrap();
        assert_eq!(lm.len(), 2);
    }

    // status: cluster-summary-staleness-counter
    // status: cluster-build-from-folders-summary-staleness
    #[test]
    fn move_node_bumps_churn_on_both_chains() {
        let (_d, trees) = open_tmp();
        let tid = trees
            .insert_tree(TreeInsert {
                id: Some("ct".into()),
                name: "t".into(),
                source: "one-shot".into(),
                state: "draft".into(),
                scope_json: "{}".into(),
                method_json: "{}".into(),
                vault_snapshot: None,
            })
            .unwrap();
        let mk = |id: &str, parent: Option<&str>, kind: NodeKind| NodeInsert {
            node_id: id.into(),
            parent_id: parent.map(|s| s.into()),
            kind,
            note_id: None,
            name: id.into(),
            summary: String::new(),
            user_edited_name: false,
            user_edited_summary: false,
            policy: None,
            centroid: None,
            confidence: 1.0,
            summary_membership_churn: 0,
        };
        trees
            .insert_nodes(
                &tid,
                &[
                    mk("root", None, NodeKind::Cluster),
                    mk("a", Some("root"), NodeKind::Cluster),
                    mk("b", Some("root"), NodeKind::Cluster),
                    NodeInsert {
                        node_id: "leaf-x".into(),
                        parent_id: Some("a".into()),
                        kind: NodeKind::Leaf,
                        note_id: Some("note-x".into()),
                        name: "x".into(),
                        summary: String::new(),
                        user_edited_name: false,
                        user_edited_summary: false,
                        policy: None,
                        centroid: None,
                        confidence: 1.0,
                        summary_membership_churn: 0,
                    },
                ],
            )
            .unwrap();
        trees.move_node(&tid, "leaf-x", Some("b")).unwrap();
        let a = trees.get_node(&tid, "a").unwrap().unwrap();
        let b = trees.get_node(&tid, "b").unwrap().unwrap();
        let root = trees.get_node(&tid, "root").unwrap().unwrap();
        // Old direct parent and new direct parent each get +1: their
        // subtree leaf set changed.
        assert_eq!(a.summary_membership_churn, 1);
        assert_eq!(b.summary_membership_churn, 1);
        // Root is the LCA of `a` and `b` — its subtree's leaf set is
        // unchanged by an internal move, so it should NOT bump.
        assert_eq!(root.summary_membership_churn, 0);
        // Regenerate resets just one node.
        trees.reset_churn(&tid, "a").unwrap();
        let a = trees.get_node(&tid, "a").unwrap().unwrap();
        assert_eq!(a.summary_membership_churn, 0);
    }

    // status: cluster-summary-staleness-counter
    //
    // Splitting a cluster `p` into sub-clusters and reparenting leaves
    // is a purely internal reshape of `p`'s subtree, but each new
    // sub-cluster legitimately gains a leaf — so `reparent_many` bumps
    // churn on each destination sub-cluster, but NOT on the LCA (`p`)
    // or anything above it. Wrapping ops (e.g. `cluster_op_split`)
    // reset churn on the freshly-inserted sub-clusters, since their
    // summaries are generated against the moved-in leaves.
    #[test]
    fn split_within_subtree_bumps_only_new_subclusters() {
        let (_d, trees) = open_tmp();
        let tid = trees
            .insert_tree(TreeInsert {
                id: Some("split-churn".into()),
                name: "t".into(),
                source: "one-shot".into(),
                state: "draft".into(),
                scope_json: "{}".into(),
                method_json: "{}".into(),
                vault_snapshot: None,
            })
            .unwrap();
        let cluster = |id: &str, parent: Option<&str>| NodeInsert {
            node_id: id.into(),
            parent_id: parent.map(|s| s.into()),
            kind: NodeKind::Cluster,
            note_id: None,
            name: id.into(),
            summary: String::new(),
            user_edited_name: false,
            user_edited_summary: false,
            policy: None,
            centroid: None,
            confidence: 1.0,
            summary_membership_churn: 0,
        };
        let leaf = |id: &str, parent: &str| NodeInsert {
            node_id: id.into(),
            parent_id: Some(parent.into()),
            kind: NodeKind::Leaf,
            note_id: Some(format!("note-{id}")),
            name: id.into(),
            summary: String::new(),
            user_edited_name: false,
            user_edited_summary: false,
            policy: None,
            centroid: None,
            confidence: 1.0,
            summary_membership_churn: 0,
        };
        trees
            .insert_nodes(
                &tid,
                &[
                    cluster("root", None),
                    cluster("p", Some("root")),
                    cluster("sub-0", Some("p")),
                    cluster("sub-1", Some("p")),
                    leaf("leaf-a", "p"),
                    leaf("leaf-b", "p"),
                ],
            )
            .unwrap();
        // Reparent both leaves out of `p` and into the new sub-clusters.
        trees
            .reparent_many(
                &tid,
                &[
                    ("leaf-a".into(), Some("sub-0".into())),
                    ("leaf-b".into(), Some("sub-1".into())),
                ],
            )
            .unwrap();
        let p = trees.get_node(&tid, "p").unwrap().unwrap();
        let sub0 = trees.get_node(&tid, "sub-0").unwrap().unwrap();
        let sub1 = trees.get_node(&tid, "sub-1").unwrap().unwrap();
        let root = trees.get_node(&tid, "root").unwrap().unwrap();
        // LCA of each leaf move is `p`. The old-parent walk from `p`
        // finds itself in the new-parent ancestor set and stops without
        // bumping; the new-parent walk from each sub-cluster bumps the
        // sub-cluster and stops at `p`. Above the LCA: no visits.
        assert_eq!(p.summary_membership_churn, 0);
        assert_eq!(sub0.summary_membership_churn, 1);
        assert_eq!(sub1.summary_membership_churn, 1);
        assert_eq!(root.summary_membership_churn, 0);
    }

    // status: cluster-build-from-folders-live-update
    #[test]
    fn folder_rename_relocates_leaf_and_drops_empty_folder() {
        let (_d, trees) = open_tmp();
        let tid = trees
            .insert_tree(TreeInsert {
                id: Some("ff".into()),
                name: "ff".into(),
                source: "saved-triage".into(),
                state: "saved-as-triage".into(),
                scope_json: "{}".into(),
                method_json: "{\"kind\":\"from-folders\"}".into(),
                vault_snapshot: None,
            })
            .unwrap();
        let leaf = NodeInsert {
            node_id: "leaf-foo".into(),
            parent_id: Some("f-inbox".into()),
            kind: NodeKind::Leaf,
            note_id: Some("note-foo".into()),
            name: "foo".into(),
            summary: String::new(),
            user_edited_name: false,
            user_edited_summary: false,
            policy: None,
            centroid: None,
            confidence: 1.0,
            summary_membership_churn: 0,
        };
        let mkc = |id: &str, parent: Option<&str>| NodeInsert {
            node_id: id.into(),
            parent_id: parent.map(|s| s.into()),
            kind: NodeKind::Cluster,
            note_id: None,
            name: id.into(),
            summary: String::new(),
            user_edited_name: false,
            user_edited_summary: false,
            policy: None,
            centroid: None,
            confidence: 1.0,
            summary_membership_churn: 0,
        };
        trees
            .insert_nodes(
                &tid,
                &[mkc("root", None), mkc("f-inbox", Some("root")), leaf],
            )
            .unwrap();
        let moved = trees
            .update_for_folder_rename(&tid, "note-foo", "research")
            .unwrap();
        assert!(moved);
        // New folder cluster auto-created.
        let dest = trees.get_node(&tid, "f-research").unwrap().unwrap();
        assert!(matches!(dest.kind, NodeKind::Cluster));
        // Old folder dropped (no policy, no children left).
        let gone = trees.get_node(&tid, "f-inbox").unwrap();
        assert!(gone.is_none(), "empty folder cluster should be GC'd");
        // Leaf re-parented.
        let leaf_now = trees.get_node(&tid, "leaf-foo").unwrap().unwrap();
        assert_eq!(leaf_now.parent.as_deref(), Some("f-research"));
    }

    #[test]
    fn folder_rename_keeps_policied_empty_folder() {
        let (_d, trees) = open_tmp();
        let tid = trees
            .insert_tree(TreeInsert {
                id: Some("ff2".into()),
                name: "ff2".into(),
                source: "saved-triage".into(),
                state: "saved-as-triage".into(),
                scope_json: "{}".into(),
                method_json: "{}".into(),
                vault_snapshot: None,
            })
            .unwrap();
        let leaf = NodeInsert {
            node_id: "leaf-x".into(),
            parent_id: Some("f-inbox".into()),
            kind: NodeKind::Leaf,
            note_id: Some("note-x".into()),
            name: "x".into(),
            summary: String::new(),
            user_edited_name: false,
            user_edited_summary: false,
            policy: None,
            centroid: None,
            confidence: 1.0,
            summary_membership_churn: 0,
        };
        let mkc = |id: &str, parent: Option<&str>, policy: Option<NodePolicy>| NodeInsert {
            node_id: id.into(),
            parent_id: parent.map(|s| s.into()),
            kind: NodeKind::Cluster,
            note_id: None,
            name: id.into(),
            summary: String::new(),
            user_edited_name: false,
            user_edited_summary: false,
            policy,
            centroid: None,
            confidence: 1.0,
            summary_membership_churn: 0,
        };
        trees
            .insert_nodes(
                &tid,
                &[
                    mkc("root", None, None),
                    mkc(
                        "f-inbox",
                        Some("root"),
                        Some(NodePolicy::Tag {
                            slug: "inbox".into(),
                            require_review: false,
                        }),
                    ),
                    leaf,
                ],
            )
            .unwrap();
        trees
            .update_for_folder_rename(&tid, "note-x", "research")
            .unwrap();
        // Empty folder cluster with a policy must survive.
        let kept = trees.get_node(&tid, "f-inbox").unwrap();
        assert!(
            kept.is_some(),
            "policied empty folder should survive"
        );
    }
}
