[package]
name = "hiker-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
blake3 = "1"
pulldown-cmark.workspace = true
rusqlite.workspace = true
sqlite-vec.workspace = true
ulid.workspace = true
fastembed.workspace = true
directories.workspace = true
tokio.workspace = true
notify.workspace = true
notify-debouncer-full.workspace = true
walkdir.workspace = true

[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["rt", "sync", "macros", "time", "fs", "rt-multi-thread"] }
