services:
  ui:
    build: .
    working_dir: /app
    user: "1000:1000"
    volumes:
      - .:/app:z
    ports:
      - "127.0.0.1:1420:1420"
    command: ./node_modules/.bin/vite --host 0.0.0.0
    init: true
    stop_grace_period: 2s
